import type {
  QuickGenerateCreativity,
  QuickGeneratePreferences,
  QuickGenerateVibe,
} from "@/lib/domainGen/quickGenerate"
import type { SpecialistBrief } from "@/lib/naming-specialist/types"

export type NamingSpecialistSplit = "train" | "validation" | "test"

/**
 * Editorial input for the Auto naming-specialist challenger.
 *
 * The corpus deliberately contains no expected names. Human-curated output
 * batches live in a separate, versioned dataset so these briefs can be audited
 * without accidentally teaching candidate surfaces to the runtime code.
 */
export interface NamingSpecialistBrief {
  id: string
  split: NamingSpecialistSplit
  description: string
  vibe: QuickGenerateVibe
  creativity: QuickGenerateCreativity
  maxChars: number
  rhymeWith?: string
  blacklist?: string[]
  preferences?: QuickGeneratePreferences
  /** Editorial language/market context, present only when locale matters. */
  locale?: string
  /** Stable topic family for leakage checks and future stratified sampling. */
  semanticClusterId: string
}

/**
 * Lossless bridge to the shared capture contract. Corpus-only constraints stay
 * attached while `style` and `maxLength` make the record directly consumable
 * by the Auto specialist pipeline.
 */
export type NamingSpecialistAutoBrief = NamingSpecialistBrief & SpecialistBrief

export const NAMING_SPECIALIST_BRIEFS: readonly NamingSpecialistBrief[] = [
  // Train — Friendly (3 Direct, 5 Balanced, 2 Exploratory; 1/5/3/1 length buckets)
  {
    id: "train-friendly-coparent-pickups",
    split: "train",
    description: "After-school pickup coordination that helps separated co-parents keep handovers calm",
    vibe: "friendly",
    creativity: "direct",
    maxChars: 7,
    semanticClusterId: "family-handover-logistics",
  },
  {
    id: "train-friendly-renter-inventory",
    split: "train",
    description: "Home inventory concierge for renters recovering from burst-pipe damage",
    vibe: "friendly",
    creativity: "direct",
    maxChars: 9,
    preferences: { likedStyles: ["real_word"], preferredLength: "short" },
    semanticClusterId: "renter-household-recovery",
  },
  {
    id: "train-friendly-new-dad-voice",
    split: "train",
    description: "Private voice-note circles connecting first-time fathers during overnight feeds",
    vibe: "friendly",
    creativity: "direct",
    maxChars: 10,
    semanticClusterId: "new-parent-peer-support",
  },
  {
    id: "train-friendly-hearing-aid-repairs",
    split: "train",
    description: "Repair appointment reminders and loan-device updates for hearing-aid users",
    vibe: "friendly",
    creativity: "balanced",
    maxChars: 8,
    blacklist: ["clinic", "medical"],
    semanticClusterId: "assistive-device-service",
  },
  {
    id: "train-friendly-wardrobe-swap",
    split: "train",
    description: "Seasonal wardrobe swap club for neighbours who want clothes to stay in use",
    vibe: "friendly",
    creativity: "balanced",
    maxChars: 9,
    rhymeWith: "share",
    semanticClusterId: "neighbourhood-wardrobe-circularity",
  },
  {
    id: "train-friendly-pet-medicine",
    split: "train",
    description: "Simple medicine diary for households caring for several rescue pets",
    vibe: "friendly",
    creativity: "balanced",
    maxChars: 10,
    preferences: { likedStyles: ["evocative", "compound"], preferredLength: "medium" },
    semanticClusterId: "multi-pet-medication",
  },
  {
    id: "train-friendly-sensory-meals",
    split: "train",
    description: "Weekly meal planning for families balancing different sensory food preferences",
    vibe: "friendly",
    creativity: "balanced",
    maxChars: 11,
    semanticClusterId: "sensory-family-meals",
  },
  {
    id: "train-friendly-accessible-playdates",
    split: "train",
    description: "Playdate discovery for parents seeking accessible activities for disabled children",
    vibe: "friendly",
    creativity: "balanced",
    maxChars: 12,
    blacklist: ["special", "hero"],
    semanticClusterId: "inclusive-family-social",
  },
  {
    id: "train-friendly-apprentice-mentoring",
    split: "train",
    description: "Peer mentoring circles for apprentice electricians navigating their first year on site",
    vibe: "friendly",
    creativity: "exploratory",
    maxChars: 12,
    rhymeWith: "spark",
    semanticClusterId: "vocational-peer-mentoring",
  },
  {
    id: "train-friendly-bilingual-library",
    split: "train",
    description: "Arabic-English library clubs helping newly arrived families discover local stories together",
    vibe: "friendly",
    creativity: "exploratory",
    maxChars: 14,
    preferences: { likedStyles: ["non_english", "evocative"], preferredLength: "medium" },
    locale: "Arabic-English (United Kingdom)",
    semanticClusterId: "bilingual-library-welcome",
  },

  // Train — Premium
  {
    id: "train-premium-scent-archive",
    split: "train",
    description: "Bespoke scent archive that preserves personal travel memories as small-batch fragrances",
    vibe: "premium",
    creativity: "direct",
    maxChars: 7,
    blacklist: ["luxe", "aroma"],
    semanticClusterId: "olfactory-memory-craft",
  },
  {
    id: "train-premium-art-storage",
    split: "train",
    description: "Private art-storage coordination for collectors moving works between homes and exhibitions",
    vibe: "premium",
    creativity: "direct",
    maxChars: 9,
    preferences: { likedStyles: ["real_word", "evocative"], preferredLength: "short" },
    semanticClusterId: "collector-art-logistics",
  },
  {
    id: "train-premium-puglia-olive-estates",
    split: "train",
    description: "Guided olive-oil estate visits for design-conscious travellers exploring Puglia",
    vibe: "premium",
    creativity: "direct",
    maxChars: 10,
    locale: "Italian (Italy)",
    semanticClusterId: "puglia-culinary-estates",
  },
  {
    id: "train-premium-science-speechwriting",
    split: "train",
    description: "Executive speechwriting studio for climate scientists addressing investors and policymakers",
    vibe: "premium",
    creativity: "balanced",
    maxChars: 8,
    blacklist: ["green", "eco"],
    semanticClusterId: "expert-science-communications",
  },
  {
    id: "train-premium-maternity-rental",
    split: "train",
    description: "Luxury maternity wardrobe rental offering beautifully tailored pieces for milestone events",
    vibe: "premium",
    creativity: "balanced",
    maxChars: 9,
    semanticClusterId: "occasion-maternity-fashion",
  },
  {
    id: "train-premium-keyboard-atelier",
    split: "train",
    description: "Limited-run mechanical keyboard atelier combining precision switches with sculpted materials",
    vibe: "premium",
    creativity: "balanced",
    maxChars: 10,
    preferences: { likedStyles: ["brandable", "compound"], preferredSounds: ["cl", "or"] },
    semanticClusterId: "enthusiast-keyboard-craft",
  },
  {
    id: "train-premium-wallpaper-restoration",
    split: "train",
    description: "Heritage wallpaper restoration studio recreating lost patterns for period townhouses",
    vibe: "premium",
    creativity: "balanced",
    maxChars: 11,
    semanticClusterId: "decorative-heritage-restoration",
  },
  {
    id: "train-premium-hotel-lighting",
    split: "train",
    description: "Architectural lighting advisory for intimate hotels that want quiet evening atmosphere",
    vibe: "premium",
    creativity: "balanced",
    maxChars: 12,
    blacklist: ["lux", "luxe"],
    semanticClusterId: "boutique-hospitality-lighting",
  },
  {
    id: "train-premium-rare-tea",
    split: "train",
    description: "Rare tea sourcing club introducing connoisseurs to overlooked mountain harvests",
    vibe: "premium",
    creativity: "exploratory",
    maxChars: 12,
    rhymeWith: "leaf",
    semanticClusterId: "connoisseur-tea-sourcing",
  },
  {
    id: "train-premium-cello-cases",
    split: "train",
    description: "Handcrafted cello-case maker in Cremona serving touring soloists and conservators",
    vibe: "premium",
    creativity: "exploratory",
    maxChars: 14,
    preferences: { likedStyles: ["non_english", "brandable"], preferredLength: "long" },
    locale: "Italian (Italy)",
    semanticClusterId: "cremona-instrument-protection",
  },

  // Train — Tech
  {
    id: "train-tech-heating-leaks",
    split: "train",
    description: "Acoustic leak detection for district-heating pipes beneath dense city streets",
    vibe: "tech",
    creativity: "direct",
    maxChars: 7,
    semanticClusterId: "utility-acoustic-diagnostics",
  },
  {
    id: "train-tech-lab-sample-routing",
    split: "train",
    description: "Robotic sample routing for laboratories processing high-volume food safety tests",
    vibe: "tech",
    creativity: "direct",
    maxChars: 9,
    preferences: { likedStyles: ["compound"], preferredLength: "short" },
    semanticClusterId: "laboratory-sample-automation",
  },
  {
    id: "train-tech-museum-digital-twin",
    split: "train",
    description: "Digital twin software that protects museum collections from unstable room climates",
    vibe: "tech",
    creativity: "direct",
    maxChars: 10,
    semanticClusterId: "museum-climate-systems",
  },
  {
    id: "train-tech-port-berths",
    split: "train",
    description: "Berth allocation tools for regional ports coordinating ferries and cargo vessels",
    vibe: "tech",
    creativity: "balanced",
    maxChars: 8,
    blacklist: ["dock", "port"],
    semanticClusterId: "port-berth-operations",
  },
  {
    id: "train-tech-embedded-errors",
    split: "train",
    description: "Compiler-error visualisation for engineers debugging safety-critical embedded devices",
    vibe: "tech",
    creativity: "balanced",
    maxChars: 9,
    rhymeWith: "byte",
    semanticClusterId: "embedded-debugging-visualisation",
  },
  {
    id: "train-tech-reagent-inventory",
    split: "train",
    description: "Reagent inventory intelligence for synthetic-biology teams sharing wet-lab materials",
    vibe: "tech",
    creativity: "balanced",
    maxChars: 10,
    preferences: { likedStyles: ["brandable", "evocative"], preferredSounds: ["syn", "lab"] },
    semanticClusterId: "synthetic-biology-reagent-ops",
  },
  {
    id: "train-tech-library-footfall",
    split: "train",
    description: "Privacy-preserving footfall analytics for public libraries planning staffing and space",
    vibe: "tech",
    creativity: "balanced",
    maxChars: 11,
    semanticClusterId: "civic-footfall-privacy",
  },
  {
    id: "train-tech-offshore-edge",
    split: "train",
    description: "Edge-compute orchestration for offshore wind turbines operating along the Norwegian coast",
    vibe: "tech",
    creativity: "balanced",
    maxChars: 12,
    locale: "Norwegian (Norway)",
    semanticClusterId: "offshore-edge-operations",
  },
  {
    id: "train-tech-quantum-certificates",
    split: "train",
    description: "Quantum-safe certificate rotation for banks replacing ageing cryptographic infrastructure",
    vibe: "tech",
    creativity: "exploratory",
    maxChars: 12,
    preferences: { dislikedStyles: ["alternate_spelling"], preferredLength: "medium" },
    semanticClusterId: "post-quantum-identity",
  },
  {
    id: "train-tech-drone-airspace",
    split: "train",
    description: "Drone traffic coordination for emergency responders working above large incident scenes",
    vibe: "tech",
    creativity: "exploratory",
    maxChars: 14,
    preferences: { likedStyles: ["evocative", "short_phrase"], avoidedSounds: ["bot"] },
    semanticClusterId: "emergency-drone-airspace",
  },

  // Train — Bold
  {
    id: "train-bold-sneaker-authentication",
    split: "train",
    description: "Anti-counterfeit tracing for collectors buying and reselling vintage sneakers",
    vibe: "bold",
    creativity: "direct",
    maxChars: 7,
    semanticClusterId: "collectible-sneaker-authentication",
  },
  {
    id: "train-bold-womens-boxing",
    split: "train",
    description: "High-energy boxing club built for women training before and after office hours",
    vibe: "bold",
    creativity: "direct",
    maxChars: 9,
    preferences: { likedStyles: ["real_word", "short_phrase"], preferredLength: "short" },
    semanticClusterId: "inclusive-combat-fitness",
  },
  {
    id: "train-bold-volcanic-sauce",
    split: "train",
    description: "Volcanic hot-sauce brand using smoked island chillies and unapologetic flavour",
    vibe: "bold",
    creativity: "direct",
    maxChars: 10,
    rhymeWith: "flare",
    blacklist: ["inferno", "fire"],
    semanticClusterId: "volcanic-condiments",
  },
  {
    id: "train-bold-hospital-crisis",
    split: "train",
    description: "Crisis simulation workshops for hospital executives preparing for system-wide disruption",
    vibe: "bold",
    creativity: "balanced",
    maxChars: 8,
    semanticClusterId: "executive-crisis-training",
  },
  {
    id: "train-bold-azores-salvage",
    split: "train",
    description: "Salvage-diving expeditions exploring historic wrecks around the Azores",
    vibe: "bold",
    creativity: "balanced",
    maxChars: 9,
    preferences: { likedStyles: ["evocative", "non_english"], preferredSounds: ["mar", "az"] },
    locale: "Portuguese (Azores)",
    semanticClusterId: "azores-maritime-expedition",
  },
  {
    id: "train-bold-yerba-energy",
    split: "train",
    description: "Yerba-mate energy drink for night-shift creatives who dislike synthetic sweetness",
    vibe: "bold",
    creativity: "balanced",
    maxChars: 10,
    semanticClusterId: "natural-stimulant-beverage",
  },
  {
    id: "train-bold-demolition-robots",
    split: "train",
    description: "Remote-controlled demolition robotics for crews working inside unstable industrial sites",
    vibe: "bold",
    creativity: "balanced",
    maxChars: 11,
    blacklist: ["blast", "bot"],
    semanticClusterId: "hazardous-demolition-automation",
  },
  {
    id: "train-bold-whistleblower-cases",
    split: "train",
    description: "Whistleblower case management for newsrooms handling sensitive source material",
    vibe: "bold",
    creativity: "balanced",
    maxChars: 12,
    semanticClusterId: "newsroom-source-security",
  },
  {
    id: "train-bold-storm-documentary",
    split: "train",
    description: "Storm-chasing documentary studio filming severe weather across open plains",
    vibe: "bold",
    creativity: "exploratory",
    maxChars: 12,
    preferences: { likedStyles: ["evocative", "compound"], preferredLength: "medium" },
    semanticClusterId: "extreme-weather-media",
  },
  {
    id: "train-bold-fire-resistant-facades",
    split: "train",
    description: "Fire-resistant facade materials for architects designing homes at the edge of dry forests",
    vibe: "bold",
    creativity: "exploratory",
    maxChars: 14,
    blacklist: ["safe", "shield"],
    semanticClusterId: "wildland-building-materials",
  },

  // Train — Clean
  {
    id: "train-clean-bookshop-returns",
    split: "train",
    description: "Returns reconciliation software for independent bookshops balancing online and in-store stock",
    vibe: "clean",
    creativity: "direct",
    maxChars: 7,
    rhymeWith: "spine",
    semanticClusterId: "bookshop-returns-reconciliation",
  },
  {
    id: "train-clean-podiatry-notes",
    split: "train",
    description: "Structured appointment notes for mobile podiatrists visiting patients at home",
    vibe: "clean",
    creativity: "direct",
    maxChars: 9,
    preferences: { likedStyles: ["real_word", "compound"], preferredLength: "short" },
    semanticClusterId: "mobile-clinician-notes",
  },
  {
    id: "train-clean-dutch-customs",
    split: "train",
    description: "Customs paperwork service for Dutch micro-exporters shipping handmade goods overseas",
    vibe: "clean",
    creativity: "direct",
    maxChars: 10,
    locale: "Dutch (Netherlands)",
    semanticClusterId: "micro-export-customs",
  },
  {
    id: "train-clean-arts-grants",
    split: "train",
    description: "Grant reporting workspace for community arts venues managing several local funders",
    vibe: "clean",
    creativity: "balanced",
    maxChars: 8,
    blacklist: ["fund", "grant"],
    semanticClusterId: "arts-grant-reporting",
  },
  {
    id: "train-clean-ebike-batteries",
    split: "train",
    description: "Battery recycling compliance for bicycle shops collecting worn e-bike packs",
    vibe: "clean",
    creativity: "balanced",
    maxChars: 9,
    semanticClusterId: "ebike-battery-compliance",
  },
  {
    id: "train-clean-residence-laundry",
    split: "train",
    description: "Laundry pickup management for student residences with shared collection points",
    vibe: "clean",
    creativity: "balanced",
    maxChars: 10,
    semanticClusterId: "residence-laundry-logistics",
  },
  {
    id: "train-clean-bakery-allergens",
    split: "train",
    description: "Allergen labelling workflow for small bakeries updating recipes and packaging",
    vibe: "clean",
    creativity: "balanced",
    maxChars: 11,
    preferences: { likedStyles: ["compound", "short_phrase"], dislikedStyles: ["alternate_spelling"] },
    semanticClusterId: "bakery-allergen-compliance",
  },
  {
    id: "train-clean-audiobook-royalties",
    split: "train",
    description: "Royalty accounting for audiobook narrators working across multiple publishers",
    vibe: "clean",
    creativity: "balanced",
    maxChars: 12,
    blacklist: ["ledger", "pay"],
    semanticClusterId: "narrator-royalty-accounting",
  },
  {
    id: "train-clean-dental-calibration",
    split: "train",
    description: "Equipment calibration logs for dental laboratories producing custom restorations",
    vibe: "clean",
    creativity: "exploratory",
    maxChars: 12,
    preferences: { likedStyles: ["brandable", "real_word"], preferredSounds: ["cal", "met"] },
    semanticClusterId: "dental-lab-calibration",
  },
  {
    id: "train-clean-ferry-handovers",
    split: "train",
    description: "Shift-handover records for ferry maintenance crews inspecting vessels overnight",
    vibe: "clean",
    creativity: "exploratory",
    maxChars: 14,
    semanticClusterId: "ferry-maintenance-handover",
  },

  // Train — Playful
  {
    id: "train-playful-tabletop-journal",
    split: "train",
    description: "Tabletop roleplaying campaign journal for friends building long-running worlds together",
    vibe: "playful",
    creativity: "direct",
    maxChars: 7,
    rhymeWith: "quest",
    semanticClusterId: "tabletop-storykeeping",
  },
  {
    id: "train-playful-science-parties",
    split: "train",
    description: "Hands-on science birthday workshops that turn kitchens into safe mini laboratories",
    vibe: "playful",
    creativity: "direct",
    maxChars: 9,
    preferences: { likedStyles: ["short_phrase", "compound"], preferredLength: "short" },
    semanticClusterId: "science-party-workshops",
  },
  {
    id: "train-playful-sticker-market",
    split: "train",
    description: "Sticker marketplace connecting independent illustrators with collectors of tiny art",
    vibe: "playful",
    creativity: "direct",
    maxChars: 10,
    semanticClusterId: "illustration-collectibles",
  },
  {
    id: "train-playful-grandparent-stories",
    split: "train",
    description: "Musical bedtime-story app that lets grandparents record characters and sound effects",
    vibe: "playful",
    creativity: "balanced",
    maxChars: 8,
    blacklist: ["tale", "story"],
    semanticClusterId: "intergenerational-audio-stories",
  },
  {
    id: "train-playful-mexico-history-hunts",
    split: "train",
    description: "Spanish-language city treasure hunts that reveal overlooked neighbourhood history in Mexico City",
    vibe: "playful",
    creativity: "balanced",
    maxChars: 9,
    locale: "Spanish (Mexico)",
    semanticClusterId: "local-history-play",
  },
  {
    id: "train-playful-trail-snacks",
    split: "train",
    description: "Cheeky trail snack brand for hikers who want savoury fuel instead of sweet bars",
    vibe: "playful",
    creativity: "balanced",
    maxChars: 10,
    rhymeWith: "crunch",
    preferences: { likedStyles: ["brandable", "alternate_spelling"], preferredSounds: ["kr", "ch"] },
    semanticClusterId: "outdoor-savoury-snacks",
  },
  {
    id: "train-playful-creative-coding",
    split: "train",
    description: "Creative coding club for primary-school pupils making animations after class",
    vibe: "playful",
    creativity: "balanced",
    maxChars: 11,
    semanticClusterId: "youth-creative-computing",
  },
  {
    id: "train-playful-japanese-plant-game",
    split: "train",
    description: "Japanese plant-care game that helps co-working teams remember shared office greenery",
    vibe: "playful",
    creativity: "balanced",
    maxChars: 12,
    blacklist: ["zen", "ninja"],
    locale: "Japanese (Japan)",
    semanticClusterId: "gamified-office-plants",
  },
  {
    id: "train-playful-improv-booking",
    split: "train",
    description: "Comedy improv class booking for beginners who want low-pressure evening sessions",
    vibe: "playful",
    creativity: "exploratory",
    maxChars: 12,
    preferences: { likedStyles: ["evocative", "short_phrase"], preferredLength: "medium" },
    semanticClusterId: "beginner-improv-classes",
  },
  {
    id: "train-playful-theatre-costumes",
    split: "train",
    description: "Costume rental platform helping amateur theatre groups share unusual stage wardrobes",
    vibe: "playful",
    creativity: "exploratory",
    maxChars: 14,
    preferences: { likedStyles: ["compound", "real_word"], dislikedStyles: ["alternate_spelling"] },
    semanticClusterId: "theatre-costume-circularity",
  },

  // Validation — intentionally separate industries and semantic clusters.
  {
    id: "validation-friendly-deaf-event-buddies",
    split: "validation",
    description: "Event buddy matching for deaf university students attending unfamiliar live venues",
    vibe: "friendly",
    creativity: "direct",
    maxChars: 9,
    locale: "British Sign Language (United Kingdom)",
    semanticClusterId: "deaf-event-companionship",
  },
  {
    id: "validation-premium-reclaimed-glass",
    split: "validation",
    description: "Contemporary glassware studio turning reclaimed window glass into sculptural table pieces",
    vibe: "premium",
    creativity: "balanced",
    maxChars: 11,
    semanticClusterId: "reclaimed-glass-design",
  },
  {
    id: "validation-tech-brewery-microbes",
    split: "validation",
    description: "Microbial monitoring for craft breweries managing fermentation across several tanks",
    vibe: "tech",
    creativity: "exploratory",
    maxChars: 12,
    semanticClusterId: "brewery-fermentation-monitoring",
  },
  {
    id: "validation-bold-rescue-races",
    split: "validation",
    description: "Team endurance race series designed for firefighters and rescue crews",
    vibe: "bold",
    creativity: "balanced",
    maxChars: 10,
    semanticClusterId: "responder-endurance-events",
  },
  {
    id: "validation-clean-cheese-provenance",
    split: "validation",
    description: "Provenance records for regional cheesemakers sharing milk sources with retailers",
    vibe: "clean",
    creativity: "direct",
    maxChars: 10,
    semanticClusterId: "artisan-dairy-provenance",
  },
  {
    id: "validation-playful-doodle-chain",
    split: "validation",
    description: "Collaborative doodle app for long-distance friends adding one line each day",
    vibe: "playful",
    creativity: "exploratory",
    maxChars: 11,
    semanticClusterId: "asynchronous-friendship-drawing",
  },
  {
    id: "validation-premium-cabin-maps",
    split: "validation",
    description: "Custom topographic print studio creating restrained maps for remote cabins",
    vibe: "premium",
    creativity: "direct",
    maxChars: 12,
    semanticClusterId: "topographic-cabin-prints",
  },
  {
    id: "validation-tech-stage-machinery",
    split: "validation",
    description: "Predictive maintenance for theatre rigging, lifts and moving stage machinery",
    vibe: "tech",
    creativity: "balanced",
    maxChars: 9,
    semanticClusterId: "theatre-machinery-maintenance",
  },
  {
    id: "validation-clean-film-permits",
    split: "validation",
    description: "Permit tracking for independent film productions working across multiple councils",
    vibe: "clean",
    creativity: "balanced",
    maxChars: 12,
    semanticClusterId: "film-production-permits",
  },
  {
    id: "validation-bold-defender-evidence",
    split: "validation",
    description: "Encrypted evidence transfer for public defenders collaborating with expert witnesses",
    vibe: "bold",
    creativity: "direct",
    maxChars: 11,
    semanticClusterId: "legal-evidence-transfer",
  },

  // Test — held apart from both training and validation topics.
  {
    id: "test-friendly-retirement-gardens",
    split: "test",
    description: "Shared garden rota for residents of retirement communities growing herbs together",
    vibe: "friendly",
    creativity: "balanced",
    maxChars: 10,
    semanticClusterId: "retirement-community-gardens",
  },
  {
    id: "test-premium-handbound-menus",
    split: "test",
    description: "Hand-bound menu studio for chef-led restaurants changing dishes with the seasons",
    vibe: "premium",
    creativity: "exploratory",
    maxChars: 13,
    semanticClusterId: "restaurant-menu-bookbinding",
  },
  {
    id: "test-tech-textile-sorting",
    split: "test",
    description: "Machine-vision sorting for textile recyclers separating blended fabrics by fibre type",
    vibe: "tech",
    creativity: "balanced",
    maxChars: 11,
    semanticClusterId: "textile-fibre-sorting",
  },
  {
    id: "test-bold-teen-oral-care",
    split: "test",
    description: "Punk-inspired oral-care brand for teenagers who reject clinical-looking products",
    vibe: "bold",
    creativity: "direct",
    maxChars: 9,
    semanticClusterId: "teen-oral-care",
  },
  {
    id: "test-clean-documentary-credentials",
    split: "test",
    description: "Crew credential tracking for documentary productions filming in remote locations",
    vibe: "clean",
    creativity: "direct",
    maxChars: 10,
    semanticClusterId: "documentary-crew-credentials",
  },
  {
    id: "test-playful-audio-scavenger",
    split: "test",
    description: "Audio scavenger hunts for conversation clubs practising a new language outdoors",
    vibe: "playful",
    creativity: "balanced",
    maxChars: 12,
    semanticClusterId: "outdoor-language-play",
  },
  {
    id: "test-premium-sculpture-commissioning",
    split: "test",
    description: "Concierge for commissioning site-specific sculpture from emerging artists",
    vibe: "premium",
    creativity: "balanced",
    maxChars: 12,
    semanticClusterId: "sculpture-commissioning",
  },
  {
    id: "test-tech-game-accessibility",
    split: "test",
    description: "Automated accessibility testing for menus and subtitles inside video games",
    vibe: "tech",
    creativity: "exploratory",
    maxChars: 10,
    semanticClusterId: "game-interface-accessibility",
  },
  {
    id: "test-clean-laundry-water",
    split: "test",
    description: "Water-use reporting for independent laundries reducing waste across several branches",
    vibe: "clean",
    creativity: "direct",
    maxChars: 11,
    semanticClusterId: "commercial-laundry-water",
  },
  {
    id: "test-bold-festival-crowds",
    split: "test",
    description: "Real-time crowd safety alerts for music festivals operating across temporary venues",
    vibe: "bold",
    creativity: "exploratory",
    maxChars: 14,
    semanticClusterId: "festival-crowd-safety",
  },
]

export function toSpecialistAutoBrief(
  brief: NamingSpecialistBrief,
): NamingSpecialistAutoBrief {
  return {
    ...brief,
    style: "auto",
    maxLength: brief.maxChars,
  }
}

export const NAMING_SPECIALIST_AUTO_BRIEFS: readonly NamingSpecialistAutoBrief[] =
  NAMING_SPECIALIST_BRIEFS.map(toSpecialistAutoBrief)
