"use client"

import { useState } from "react"
import { CheckCircle, Copy, ExternalLink, LayoutTemplate } from "lucide-react"

interface StitchPromptProps {
  brandName: string
  keywords: string
  vibe: string
  compact?: boolean
  templateLabel?: string
  viewLabel?: string
  brandType?: string
  palette: {
    primary: { hex: string }
    secondary: { hex: string }
    accent: { hex: string }
    background: { hex: string }
    text: { hex: string }
  }
}

function buildPrompt({
  brandName,
  keywords,
  vibe,
  palette,
  templateLabel,
  viewLabel,
  brandType,
}: StitchPromptProps): string {
  const description = keywords.trim() || `a modern ${vibe} brand`
  const tagline = "Built for what's next."
  const selectedTemplate = templateLabel || brandType || "Startup"
  const selectedView = viewLabel || "Landing"

  return `MASTER STITCH PROMPT (AUTO-GENERATED BY NAMOLUX)

Create a high-quality, modern startup UI system using the following inputs.

Brand Name:
${brandName}

Brand Description:
${description}

Tagline:
${tagline}

Brand Personality:
${vibe.charAt(0).toUpperCase() + vibe.slice(1)}

Brand Type / Industry Mode:
${brandType || selectedTemplate}

Selected Sandbox Template:
${selectedTemplate}

Selected Preview Context:
${selectedView}

Color Palette:
- Primary: ${palette.primary.hex.toUpperCase()}
- Secondary: ${palette.secondary.hex.toUpperCase()}
- Accent: ${palette.accent.hex.toUpperCase()}
- Background: ${palette.background.hex.toUpperCase()}
- Text: ${palette.text.hex.toUpperCase()}

----------------------------------------

DESIGN STYLE:

- Premium, modern, production-ready UI, not a concept sketch
- Clean spacing, strong hierarchy, and readable typography
- Mobile-first design that also scales cleanly to desktop
- Industry-aware layout and copy based on the selected template
- Include real product, dashboard, proof, and offer details where relevant
- Avoid generic AI design styles, purple gradients, clutter, and placeholder blocks

----------------------------------------

REQUIRED UI SYSTEM:

1. Landing / Hero
- Strong headline using the brand tone
- Subheadline using the brand description
- Primary and secondary CTA buttons
- Product, brand, storefront, app, editorial, or dashboard visual area with real-looking content

2. Product / Feature Section
- 3 to 4 key benefits based on the brand description
- Make features specific to the industry mode
- Avoid placeholder grey bars unless they are intentional UI chrome

3. Dashboard / Proof Context
- Include at least 3 meaningful metrics or stat cards
- Add dashboard, app, storefront, editorial, developer, finance, wellness, or creative modules that fit the selected template

4. Social Proof / Trust
- Testimonial, review, trust, or credibility indicator
- Clean, minimal presentation

5. Pricing / CTA
- Reinforce the tagline
- Strong CTA button
- Offer or plan cards where appropriate

----------------------------------------

COLOR USAGE RULES:

- Use Primary color for main CTAs and key highlights
- Use Secondary color for supporting UI elements, surfaces, cards, or borders
- Use Accent color sparingly for badges, charts, progress, or emphasis
- Background should remain clean and readable
- Text must maintain strong contrast

----------------------------------------

TYPOGRAPHY:

- Clean modern sans-serif for most brands
- If luxury brand, use a refined serif for headings
- Ensure readable line lengths, spacing, and button labels

----------------------------------------

TONE:

Adapt the visual tone to the brand:
- Playful: soft shapes, rounded UI, approachable copy
- Luxury: minimal, spacious, editorial, refined
- Tech/SaaS: sharp, structured, modern, dashboard-led
- Natural/Wellness: soft, earthy, calm, progress-led
- Fintech: secure, precise, trustworthy
- Dev tool: docs, API, status, terminal or command-center feel
- Mobile app: onboarding, app screen hierarchy, thumb-friendly actions

----------------------------------------

IMPORTANT:

- Do not explain the design
- Do not describe the brand in prose outside the UI
- Output should look like a real startup product/brand system
- Keep it clean, structured, premium, and realistic

----------------------------------------

GOAL:

The result should look like:
"A real startup brand system someone would pay GBP 1,000+ for"`
}

export function StitchPrompt({
  brandName,
  keywords,
  vibe,
  palette,
  compact = false,
  templateLabel,
  viewLabel,
  brandType,
}: StitchPromptProps) {
  const [copied, setCopied] = useState(false)
  const [expanded, setExpanded] = useState(false)

  const prompt = buildPrompt({ brandName, keywords, vibe, palette, compact, templateLabel, viewLabel, brandType })

  function copyPrompt() {
    navigator.clipboard.writeText(prompt).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    })
  }

  if (compact) {
    return (
      <div
        className="overflow-hidden rounded-xl"
        style={{
          background: "rgba(96,165,250,0.035)",
          border: "1px solid rgba(96,165,250,0.14)",
        }}
      >
        <div className="flex flex-col gap-3 px-4 py-3 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex min-w-0 items-center gap-3">
            <div
              className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg"
              style={{ background: "rgba(96,165,250,0.1)", border: "1px solid rgba(96,165,250,0.18)" }}
            >
              <LayoutTemplate className="h-3.5 w-3.5" style={{ color: "#60a5fa" }} />
            </div>
            <div className="min-w-0">
              <p className="truncate text-xs font-bold text-white">Advanced export: Stitch prompt</p>
              <p className="mt-0.5 truncate text-[10px]" style={{ color: "rgba(255,255,255,0.28)" }}>
                Optional fallback with the selected template, palette, and preview context.
              </p>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-2 sm:flex sm:items-center">
            <button
              onClick={() => setExpanded((value) => !value)}
              className="min-h-9 rounded-lg px-3 py-2 text-[10px] font-bold transition-colors hover:text-white"
              style={{
                background: "rgba(255,255,255,0.035)",
                border: "1px solid rgba(255,255,255,0.08)",
                color: "rgba(96,165,250,0.88)",
              }}
              type="button"
            >
              {expanded ? "Hide" : "View"}
            </button>
            <button
              onClick={copyPrompt}
              className="flex min-h-9 items-center justify-center gap-1.5 rounded-lg px-3 py-2 text-[10px] font-bold transition-all"
              style={
                copied
                  ? {
                      background: "rgba(52,211,153,0.12)",
                      border: "1px solid rgba(52,211,153,0.25)",
                      color: "#34d399",
                    }
                  : {
                      background: "rgba(96,165,250,0.1)",
                      border: "1px solid rgba(96,165,250,0.22)",
                      color: "#60a5fa",
                    }
              }
              type="button"
            >
              {copied ? <CheckCircle className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
              {copied ? "Copied" : "Copy"}
            </button>
            <a
              href="https://stitch.withgoogle.com"
              target="_blank"
              rel="noopener noreferrer"
              className="flex min-h-9 items-center justify-center gap-1.5 rounded-lg px-3 py-2 text-[10px] font-bold transition-all"
              style={{
                background: "rgba(255,255,255,0.035)",
                border: "1px solid rgba(255,255,255,0.08)",
                color: "rgba(255,255,255,0.52)",
              }}
            >
              <ExternalLink className="h-3.5 w-3.5" />
              Open
            </a>
          </div>
        </div>

        {expanded && (
          <div
            className="max-h-60 overflow-y-auto px-4 py-3"
            style={{ borderTop: "1px solid rgba(96,165,250,0.1)" }}
          >
            <pre
              className="whitespace-pre-wrap font-mono text-[10px] leading-relaxed"
              style={{ color: "rgba(255,255,255,0.44)" }}
            >
              {prompt}
            </pre>
          </div>
        )}
      </div>
    )
  }

  return (
    <div
      className="overflow-hidden rounded-2xl"
      style={{
        background: "rgba(96,165,250,0.04)",
        border: "1px solid rgba(96,165,250,0.18)",
      }}
    >
      <div
        className="flex items-center justify-between gap-3 px-5 py-4"
        style={{ borderBottom: "1px solid rgba(96,165,250,0.1)" }}
      >
        <div className="flex items-center gap-3">
          <div
            className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl"
            style={{ background: "rgba(96,165,250,0.12)", border: "1px solid rgba(96,165,250,0.2)" }}
          >
            <LayoutTemplate className="h-4 w-4" style={{ color: "#60a5fa" }} />
          </div>
          <div>
            <p className="text-sm font-bold text-white">Landing Page Template</p>
            <p className="text-[11px]" style={{ color: "rgba(255,255,255,0.35)" }}>
              Ready-to-use Stitch prompt with your colours, brand, and template pre-filled
            </p>
          </div>
        </div>

        <button
          onClick={() => setExpanded((value) => !value)}
          className="text-[11px] font-semibold transition-colors hover:text-white"
          style={{ color: "rgba(96,165,250,0.8)" }}
          type="button"
        >
          {expanded ? "Hide prompt" : "View prompt"}
        </button>
      </div>

      {expanded && (
        <div
          className="max-h-64 overflow-y-auto px-5 py-4"
          style={{ borderBottom: "1px solid rgba(96,165,250,0.08)" }}
        >
          <pre
            className="whitespace-pre-wrap font-mono text-[10px] leading-relaxed"
            style={{ color: "rgba(255,255,255,0.45)" }}
          >
            {prompt}
          </pre>
        </div>
      )}

      <div className="flex flex-wrap items-center gap-3 px-5 py-4">
        <button
          onClick={copyPrompt}
          className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold transition-all hover:-translate-y-0.5"
          style={
            copied
              ? {
                  background: "rgba(52,211,153,0.12)",
                  border: "1px solid rgba(52,211,153,0.25)",
                  color: "#34d399",
                  boxShadow: "0 4px 16px rgba(52,211,153,0.1)",
                }
              : {
                  background: "rgba(96,165,250,0.12)",
                  border: "1px solid rgba(96,165,250,0.25)",
                  color: "#60a5fa",
                  boxShadow: "0 4px 16px rgba(96,165,250,0.08)",
                }
          }
          type="button"
        >
          {copied ? (
            <>
              <CheckCircle className="h-4 w-4" /> Prompt copied!
            </>
          ) : (
            <>
              <Copy className="h-4 w-4" /> Copy Stitch prompt
            </>
          )}
        </button>

        <a
          href="https://stitch.withgoogle.com"
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition-all hover:-translate-y-0.5"
          style={{
            background: "rgba(255,255,255,0.04)",
            border: "1px solid rgba(255,255,255,0.1)",
            color: "rgba(255,255,255,0.55)",
          }}
        >
          <ExternalLink className="h-4 w-4" />
          Open Stitch
        </a>
      </div>

      <div className="px-5 pb-4">
        <p className="text-[10px] leading-relaxed" style={{ color: "rgba(255,255,255,0.2)" }}>
          1. Copy the prompt above &nbsp;-&nbsp; 2. Open Stitch &nbsp;-&nbsp; 3. Paste and generate the brand system
        </p>
      </div>
    </div>
  )
}
