"use client"

import { useState } from "react"
import { Copy, CheckCircle, ExternalLink, LayoutTemplate } from "lucide-react"

interface StitchPromptProps {
  brandName: string
  keywords: string
  vibe: string
  palette: {
    primary: { hex: string }
    secondary: { hex: string }
    accent: { hex: string }
    background: { hex: string }
    text: { hex: string }
  }
}

function buildPrompt(
  brandName: string,
  keywords: string,
  vibe: string,
  palette: StitchPromptProps["palette"],
): string {
  const description = keywords.trim() || `a modern ${vibe} brand`
  const tagline = `Built for what's next.`

  return `MASTER STITCH PROMPT (AUTO-GENERATED BY NAMOLUX)

Create a high-quality, modern landing page UI for a startup brand using the following inputs.

Brand Name:
${brandName}

Brand Description:
${description}

Tagline:
${tagline}

Brand Personality:
${vibe.charAt(0).toUpperCase() + vibe.slice(1)}

Color Palette:
- Primary: ${palette.primary.hex.toUpperCase()}
- Secondary: ${palette.secondary.hex.toUpperCase()}
- Accent: ${palette.accent.hex.toUpperCase()}
- Background: ${palette.background.hex.toUpperCase()}
- Text: ${palette.text.hex.toUpperCase()}

----------------------------------------

DESIGN STYLE:

- Premium, modern, production-ready UI (not a concept design)
- Clean spacing, strong hierarchy
- Mobile-first design (must look excellent on mobile screens)
- Scalable to desktop
- Smooth, minimal, high-end feel
- Avoid generic AI design styles (no purple gradients, no clutter)

----------------------------------------

LAYOUT STRUCTURE:

1. Hero Section
- Strong headline using the brand tone
- Subheadline using brand description
- Primary CTA button
- Clean visual area (product / abstract UI / lifestyle)

2. Features Section
- 3–4 key benefits based on brand description
- Card-based layout
- Simple icons or visual indicators

3. Product / Experience Section
- Showcase how the product/service works
- Use modern UI blocks or product visuals

4. Social Proof / Trust
- Testimonials or credibility indicators
- Clean minimal design

5. Call To Action Section
- Reinforce tagline
- Strong CTA button

----------------------------------------

COLOR USAGE RULES:

- Use Primary color for main CTAs and key highlights
- Use Secondary color for supporting UI elements
- Use Accent color sparingly for emphasis
- Background should remain clean and readable
- Text must maintain strong contrast

----------------------------------------

TYPOGRAPHY:

- Clean modern sans-serif for most brands
- If luxury brand → use serif for headings
- Ensure readability and spacing

----------------------------------------

TONE:

Adapt the visual tone to the brand:
- Playful → soft shapes, rounded UI
- Luxury → minimal, spaced, elegant
- Tech → sharp, structured, modern
- Natural → soft, earthy, calm

----------------------------------------

IMPORTANT:

- Do NOT explain the design
- Do NOT describe the brand
- Output should look like a real landing page UI
- Keep it clean, structured, and realistic

----------------------------------------

GOAL:

The result should look like:
"A real startup landing page someone would pay £1,000+ for"`
}

export function StitchPrompt({ brandName, keywords, vibe, palette }: StitchPromptProps) {
  const [copied, setCopied] = useState(false)
  const [expanded, setExpanded] = useState(false)

  const prompt = buildPrompt(brandName, keywords, vibe, palette)

  function copyPrompt() {
    navigator.clipboard.writeText(prompt).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    })
  }

  return (
    <div
      className="overflow-hidden rounded-2xl"
      style={{
        background: "rgba(96,165,250,0.04)",
        border: "1px solid rgba(96,165,250,0.18)",
      }}
    >
      {/* Header */}
      <div
        className="flex items-center justify-between gap-3 px-5 py-4"
        style={{ borderBottom: "1px solid rgba(96,165,250,0.1)" }}
      >
        <div className="flex items-center gap-3">
          <div
            className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl"
            style={{ background: "rgba(96,165,250,0.12)", border: "1px solid rgba(96,165,250,0.2)" }}
          >
            <LayoutTemplate className="h-4 w-4" style={{ color: "#60a5fa" }} />
          </div>
          <div>
            <p className="text-sm font-bold text-white">Landing Page Template</p>
            <p className="text-[11px]" style={{ color: "rgba(255,255,255,0.35)" }}>
              Ready-to-use Stitch prompt — your colours and brand pre-filled
            </p>
          </div>
        </div>

        {/* Expand/collapse toggle */}
        <button
          onClick={() => setExpanded((v) => !v)}
          className="text-[11px] font-semibold transition-colors hover:text-white"
          style={{ color: "rgba(96,165,250,0.8)" }}
        >
          {expanded ? "Hide prompt" : "View prompt"}
        </button>
      </div>

      {/* Prompt preview (expandable) */}
      {expanded && (
        <div
          className="max-h-64 overflow-y-auto px-5 py-4"
          style={{ borderBottom: "1px solid rgba(96,165,250,0.08)" }}
        >
          <pre
            className="whitespace-pre-wrap font-mono text-[10px] leading-relaxed"
            style={{ color: "rgba(255,255,255,0.45)" }}
          >
            {prompt}
          </pre>
        </div>
      )}

      {/* Actions */}
      <div className="flex flex-wrap items-center gap-3 px-5 py-4">
        {/* Copy prompt */}
        <button
          onClick={copyPrompt}
          className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold transition-all hover:-translate-y-0.5"
          style={
            copied
              ? {
                  background: "rgba(52,211,153,0.12)",
                  border: "1px solid rgba(52,211,153,0.25)",
                  color: "#34d399",
                  boxShadow: "0 4px 16px rgba(52,211,153,0.1)",
                }
              : {
                  background: "rgba(96,165,250,0.12)",
                  border: "1px solid rgba(96,165,250,0.25)",
                  color: "#60a5fa",
                  boxShadow: "0 4px 16px rgba(96,165,250,0.08)",
                }
          }
        >
          {copied ? (
            <><CheckCircle className="h-4 w-4" /> Prompt copied!</>
          ) : (
            <><Copy className="h-4 w-4" /> Copy Stitch prompt</>
          )}
        </button>

        {/* Open Stitch */}
        <a
          href="https://stitch.withgoogle.com"
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition-all hover:-translate-y-0.5"
          style={{
            background: "rgba(255,255,255,0.04)",
            border: "1px solid rgba(255,255,255,0.1)",
            color: "rgba(255,255,255,0.55)",
          }}
        >
          <ExternalLink className="h-4 w-4" />
          Open Stitch
        </a>
      </div>

      {/* How-to hint */}
      <div
        className="px-5 pb-4"
      >
        <p className="text-[10px] leading-relaxed" style={{ color: "rgba(255,255,255,0.2)" }}>
          1. Copy the prompt above &nbsp;·&nbsp; 2. Open Stitch &nbsp;·&nbsp; 3. Paste and generate your landing page
        </p>
      </div>
    </div>
  )
}
