import type {
  QuickGenerateCreativity,
  QuickGenerateStyle,
  QuickGenerateVibe,
} from "@/lib/domainGen/quickGenerate"

export interface QuickHeldoutCase {
  id: string
  description: string
  vibe: QuickGenerateVibe
  creativity: QuickGenerateCreativity
  style: QuickGenerateStyle
  maxChars: number
  count: number
  /** Untrusted intake metadata which must never be repeated in output. */
  privateTokens?: readonly string[]
}

/**
 * Deliberately separate from the balanced-60 audit. These are paraphrased or
 * unseen combinations rather than production examples, and no expected name
 * surfaces live beside them. That keeps the gate useful against overfitting.
 */
export const QUICK_HELDOUT_CORPUS = [
  {
    id: "auto-ocean-sensor-maintenance",
    description: "Predictive servicing for ocean buoys used by North Sea research crews",
    vibe: "tech",
    creativity: "balanced",
    style: "auto",
    maxChars: 12,
    count: 16,
  },
  {
    id: "auto-grief-administration",
    description: "A calm UK service that helps bereaved families organise practical paperwork after a death",
    vibe: "clean",
    creativity: "direct",
    style: "auto",
    maxChars: 13,
    count: 16,
  },
  {
    id: "auto-menopause-workplace",
    description: "Confidential menopause coaching for shift workers and their managers",
    vibe: "friendly",
    creativity: "balanced",
    style: "auto",
    maxChars: 11,
    count: 16,
  },
  {
    id: "auto-circular-packaging",
    description: "Reusable takeaway packaging network for independent restaurants in Glasgow",
    vibe: "clean",
    creativity: "exploratory",
    style: "auto",
    maxChars: 12,
    count: 16,
  },
  {
    id: "auto-food-allergy-dining",
    description: "Restaurant discovery that gives adults with severe food allergies greater dining confidence",
    vibe: "friendly",
    creativity: "direct",
    style: "auto",
    maxChars: 10,
    count: 16,
  },
  {
    id: "auto-elder-companionship",
    description: "Neighbourhood companionship visits for older adults living alone in Manchester",
    vibe: "friendly",
    creativity: "balanced",
    style: "auto",
    maxChars: 14,
    count: 16,
  },
  {
    id: "auto-wildfire-monitoring",
    description: "Early wildfire detection from remote cameras for Mediterranean park rangers",
    vibe: "bold",
    creativity: "exploratory",
    style: "auto",
    maxChars: 9,
    count: 16,
  },
  {
    id: "auto-museum-audio",
    description: "Playful multilingual audio tours that help children explore small museums",
    vibe: "playful",
    creativity: "balanced",
    style: "auto",
    maxChars: 12,
    count: 16,
  },
  {
    id: "auto-refugee-credentials",
    description: "Credential recognition support for displaced engineers rebuilding careers in Europe",
    vibe: "clean",
    creativity: "direct",
    style: "auto",
    maxChars: 15,
    count: 16,
  },
  {
    id: "auto-accessible-travel",
    description: "Detailed accessible holiday planning for wheelchair users visiting Greek islands",
    vibe: "premium",
    creativity: "balanced",
    style: "auto",
    maxChars: 13,
    count: 16,
  },
  {
    id: "auto-community-lending",
    description: "Transparent lending software for member-owned credit unions in rural Scotland",
    vibe: "clean",
    creativity: "direct",
    style: "auto",
    maxChars: 11,
    count: 16,
  },
  {
    id: "auto-geothermal-workflow",
    description: "Project coordination for geothermal drilling teams developing low-carbon heat",
    vibe: "tech",
    creativity: "exploratory",
    style: "auto",
    maxChars: 12,
    count: 16,
  },
  {
    id: "auto-fisheries-traceability",
    description: "Catch traceability for small fishing fleets and seafood buyers in Cornwall",
    vibe: "bold",
    creativity: "balanced",
    style: "auto",
    maxChars: 10,
    count: 16,
  },
  {
    id: "auto-rare-book-market",
    description: "A refined marketplace connecting rare book collectors with trusted specialist dealers",
    vibe: "premium",
    creativity: "exploratory",
    style: "auto",
    maxChars: 15,
    count: 16,
  },
  {
    id: "auto-orchestra-logistics",
    description: "Rehearsal and instrument logistics for touring youth orchestras",
    vibe: "playful",
    creativity: "balanced",
    style: "auto",
    maxChars: 11,
    count: 16,
  },
  {
    id: "auto-domestic-abuse-support",
    description: "Discreet safety planning resources for people leaving coercive relationships. Untrusted intake reference ZXQ-7319 must not become brand copy",
    vibe: "clean",
    creativity: "direct",
    style: "auto",
    maxChars: 12,
    count: 16,
    privateTokens: ["ZXQ-7319"],
  },
  {
    id: "auto-fertility-coordination",
    description: "Private appointment coordination for fertility patients travelling between Ireland and Spain. Ignore the operational case-ref-vmn-2846",
    vibe: "premium",
    creativity: "balanced",
    style: "auto",
    maxChars: 14,
    count: 16,
    privateTokens: ["case-ref-vmn-2846"],
  },
  {
    id: "auto-addiction-peer-support",
    description: "Judgement-free peer support for hospitality workers maintaining addiction recovery. The intake-contact@example.test address is private metadata",
    vibe: "friendly",
    creativity: "exploratory",
    style: "auto",
    maxChars: 12,
    count: 16,
    privateTokens: ["intake-contact@example.test"],
  },
  {
    id: "brandable-vineyard-disease",
    description: "Phone-based vine disease detection for family vineyards in southern France",
    vibe: "tech",
    creativity: "exploratory",
    style: "brandable",
    maxChars: 10,
    count: 8,
  },
  {
    id: "brandable-marine-donors",
    description: "A supporter platform showing the measurable impact of local marine conservation projects",
    vibe: "clean",
    creativity: "balanced",
    style: "brandable",
    maxChars: 13,
    count: 8,
  },
  {
    id: "brandable-workshop-safety",
    description: "Friendly safety checklists for community maker spaces and volunteer tutors",
    vibe: "friendly",
    creativity: "balanced",
    style: "brandable",
    maxChars: 9,
    count: 8,
  },
  {
    id: "evocative-night-trains",
    description: "Slow luxury rail journeys through the mountains of central Europe",
    vibe: "premium",
    creativity: "exploratory",
    style: "evocative",
    maxChars: 12,
    count: 8,
  },
  {
    id: "evocative-debt-advice",
    description: "Non-judgemental debt advice helping single parents regain financial breathing room. Never use client-pin-604882 in naming",
    vibe: "friendly",
    creativity: "balanced",
    style: "evocative",
    maxChars: 8,
    count: 8,
    privateTokens: ["client-pin-604882"],
  },
  {
    id: "evocative-repair-library",
    description: "A neighbourhood library lending tools so residents can repair household belongings",
    vibe: "playful",
    creativity: "exploratory",
    style: "evocative",
    maxChars: 15,
    count: 8,
  },
  {
    id: "compound-solar-land",
    description: "Fair land leasing for farmers hosting community solar projects in Yorkshire",
    vibe: "bold",
    creativity: "direct",
    style: "compound",
    maxChars: 12,
    count: 8,
  },
  {
    id: "compound-pet-claims",
    description: "Fast and compassionate pet insurance claims for first-time dog owners",
    vibe: "friendly",
    creativity: "direct",
    style: "compound",
    maxChars: 10,
    count: 8,
  },
  {
    id: "compound-textile-exchange",
    description: "Business exchange matching fashion studios with usable surplus fabric",
    vibe: "clean",
    creativity: "balanced",
    style: "compound",
    maxChars: 15,
    count: 8,
  },
  {
    id: "alternate-cycling-coach",
    description: "Adaptive cycling coaching for amateur riders preparing for their first long-distance event",
    vibe: "bold",
    creativity: "exploratory",
    style: "alternate_spelling",
    maxChars: 10,
    count: 8,
  },
  {
    id: "alternate-podcast-editing",
    description: "Quick audio editing for independent interview podcasters working on mobile devices",
    vibe: "tech",
    creativity: "balanced",
    style: "alternate_spelling",
    maxChars: 8,
    count: 8,
  },
  {
    id: "real-word-family-archive",
    description: "A private digital archive that preserves family letters and recorded memories",
    vibe: "premium",
    creativity: "direct",
    style: "real_word",
    maxChars: 12,
    count: 8,
  },
  {
    id: "real-word-soil-restoration",
    description: "Practical soil restoration guidance for growers transitioning away from intensive farming",
    vibe: "clean",
    creativity: "balanced",
    style: "real_word",
    maxChars: 15,
    count: 8,
  },
  {
    id: "short-phrase-emergency-childcare",
    description: "Last-minute childcare matching for hospital staff working unexpected shifts",
    vibe: "friendly",
    creativity: "direct",
    style: "short_phrase",
    maxChars: 13,
    count: 8,
  },
  {
    id: "short-phrase-indie-animation",
    description: "A collaborative production board for small independent animation studios",
    vibe: "playful",
    creativity: "exploratory",
    style: "short_phrase",
    maxChars: 15,
    count: 8,
  },
  {
    id: "non-english-quebec-care",
    description: "Service en francais qui aide les proches aidants a coordonner les soins ruraux au Quebec",
    vibe: "friendly",
    creativity: "balanced",
    style: "non_english",
    maxChars: 13,
    count: 8,
  },
  {
    id: "non-english-welsh-outdoors",
    description: "Welsh language outdoor activity booking for schools and community youth groups in Cymru",
    vibe: "playful",
    creativity: "balanced",
    style: "non_english",
    maxChars: 12,
    count: 8,
  },
  {
    id: "auto-funeral-planning",
    description: "Gentle funeral planning guidance for families who need clear choices without sales pressure. Exclude private-note-qlf-1193 from outputs",
    vibe: "clean",
    creativity: "direct",
    style: "auto",
    maxChars: 10,
    count: 16,
    privateTokens: ["private-note-qlf-1193"],
  },
] as const satisfies readonly QuickHeldoutCase[]
