import type { Metadata } from "next"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"

export const metadata: Metadata = {
  title: "Terms of Service | NamoLux",
  description:
    "Review the NamoLux terms of service covering credits, availability checks, acceptable use, and your responsibilities when generating domains with NamoLux.",
  twitter: {
    card: "summary",
    title: "Terms of Service | NamoLux",
    description:
      "Review the NamoLux terms of service covering credits, availability checks, acceptable use, and your responsibilities when generating domains with NamoLux.",
  },
}

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <main className="flex-1 px-4 pt-24 pb-16">
        <div className="mx-auto max-w-3xl">
          <h1 className="mb-8 text-4xl font-bold text-foreground">Terms of Service</h1>
          
          <div className="prose prose-invert max-w-none space-y-6 text-muted-foreground">
            <p className="text-lg">Last updated: January 2026</p>
            
            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">1. Acceptance of Terms</h2>
              <p>
                By accessing or using NamoLux, you agree to be bound by these Terms of Service. 
                If you do not agree to these terms, please do not use our service.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">2. Description of Service</h2>
              <p>
                NamoLux provides an AI-powered domain name generation service. We help users discover 
                available domain names based on keywords and preferences. We do not register domains 
                directly - we provide links to third-party registrars.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">3. Credits and Payments</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>Credits are required to generate domain names</li>
                <li>Credits are non-refundable once purchased</li>
                <li>Credits do not expire</li>
                <li>Each domain generation costs 1 credit</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">4. Domain Availability</h2>
              <p>
                Domain availability is checked in real-time but we cannot guarantee that a domain 
                will still be available when you attempt to register it. Domain registration is 
                handled by third-party registrars and is subject to their terms and pricing.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">5. Intellectual Property</h2>
              <p>
                The domain names generated by NamoLux are suggestions only. We do not claim ownership 
                over any domain names generated. Users are responsible for ensuring that domain names 
                do not infringe on existing trademarks.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">6. Limitation of Liability</h2>
              <p>
                NamoLux is provided &ldquo;as is&rdquo; without warranties of any kind. We are not liable 
                for any damages arising from the use of our service.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">7. Contact</h2>
              <p>
                For questions about these Terms, contact us at{" "}
                <a href="mailto:support@namolux.com" className="text-primary hover:underline">
                  support@namolux.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
