import type { BlogPost } from "@/lib/blog"

export const priorityNamingPosts: BlogPost[] = [
  {
    slug: "how-to-check-if-business-name-is-taken",
    title: "How to Check If a Business Name Is Taken: A Four-Database Clearance Workflow",
    description: "A practical workflow for checking company-name and trademark conflicts across the UK, US and EU before you commit to a brand.",
    seoTitle: "How to Check If a Business Name Is Taken",
    metaDescription: "Use a practical four-database workflow to check company-name and trademark conflicts in the UK, US and EU before you launch.",
    category: "Domain Strategy",
    readTime: 8,
    publishedAt: "2026-07-11",
    updatedAt: "2026-07-11",
    author: "Andrew Barrett",
    qualityTier: "priority",
    primaryKeyword: "how to check if a business name is taken",
    searchIntent: "commercial",
    pillar: "Name Clearance & IP",
    tags: ["business name search", "company register", "trademark search", "UKIPO", "USPTO", "EUIPO"],
    relatedSlugs: [
      "how-to-come-up-with-a-business-name",
      "domain-validation-checklist",
      "international-brand-name-checks",
      "how-to-choose-a-domain-name",
      "secure-brand-across-platforms",
    ],
    sources: [
      {
        title: "Choose a company name",
        url: "https://www.gov.uk/limited-company-formation/choose-company-name",
        authority: "Companies House / GOV.UK",
        lastVerified: "2026-07-11",
      },
      {
        title: "Choose your business name",
        url: "https://www.sba.gov/business-guide/launch-your-business/choose-your-business-name",
        authority: "U.S. Small Business Administration",
        lastVerified: "2026-07-11",
      },
      {
        title: "Search for a trade mark",
        url: "https://www.gov.uk/search-for-trademark",
        authority: "UK Intellectual Property Office / GOV.UK",
        lastVerified: "2026-07-11",
      },
      {
        title: "Federal trademark searching",
        url: "https://www.uspto.gov/trademarks/search/federal-trademark-searching",
        authority: "United States Patent and Trademark Office",
        lastVerified: "2026-07-11",
      },
      {
        title: "Availability and TMview",
        url: "https://www.euipo.europa.eu/en/trade-marks/before-applying/availability",
        authority: "European Union Intellectual Property Office",
        lastVerified: "2026-07-11",
      },
    ],
    content: [
      {
        type: "paragraph",
        content: "Finding no exact match in one search box does not prove that a business name is available. A name can pass a company-register search but conflict with a trade mark. Its domain can be available while another company has earlier brand rights. It can also be usable in one country and risky in another.",
      },
      {
        type: "paragraph",
        content: "The useful question is not simply ‘Is this name taken?’ It is ‘What existing names or rights could stop us registering, using or protecting this name in the markets that matter?’ If you are still generating candidates, begin with a broad [business-name shortlist](/blog/how-to-come-up-with-a-business-name), then run every finalist through the same clearance process.",
      },
      {
        type: "callout",
        calloutType: "warning",
        content: "This article provides a practical preliminary screening workflow, not legal advice or a legal clearance opinion. Official databases are essential starting points, but they may not reveal every unregistered right, trading name or legal risk. Ask a qualified trade mark professional about close results or any name carrying meaningful launch investment.",
      },
      { type: "heading", level: 2, content: "What ‘Taken’ Can Actually Mean" },
      {
        type: "table",
        content: "",
        headers: ["Question", "What it tells you", "What it does not tell you"],
        rows: [
          ["Can I register the legal entity?", "Whether the relevant company or state register will accept the entity name", "Whether using the name infringes another brand"],
          ["Is there a registered trade mark conflict?", "Whether official registers contain earlier applications or registrations worth investigating", "Whether an unregistered business has enforceable rights"],
          ["Is the domain available?", "Whether the exact web address can currently be registered", "Whether the business name is legally safe"],
          ["Can I protect the name?", "Whether the name appears distinctive enough to investigate further", "Whether an examiner or court will ultimately accept it"],
        ],
      },
      {
        type: "paragraph",
        content: "These checks answer different questions. Treating them as interchangeable is how founders end up owning a domain for a name they cannot safely use. Complete the legal-name and trade mark screen first, then apply the broader checks in the [domain validation checklist](/blog/domain-validation-checklist).",
      },
      { type: "heading", level: 2, content: "Prepare Your Search Before Opening a Database" },
      {
        type: "paragraph",
        content: "Write down the exact name, the countries where you expect to trade, and a plain-language description of what you will sell. Trade mark results are assessed in the context of goods and services, so ‘software’ is less useful than ‘subscription software for restaurant inventory management’. Include realistic adjacent products you may launch within the next few years.",
      },
      {
        type: "list",
        content: "",
        items: [
          "Exact name, with and without spaces, punctuation and company suffixes",
          "Singular, plural and possessive forms",
          "Likely misspellings and phonetic equivalents",
          "The distinctive word or stem without generic terms",
          "Goods and services sold now, plus realistic adjacent offers",
          "Launch territories: UK, United States, European Union or another market",
        ],
      },
      { type: "heading", level: 2, content: "Database 1: The Official Legal-Entity Register" },
      {
        type: "paragraph",
        content: "For a UK limited company, search the official [Companies House register](https://find-and-update.company-information.service.gov.uk/). Search the exact name first, then remove ‘Limited’ or ‘Ltd’ and try the spelling, spacing and sound-alike variants on your worksheet. Open close results and note whether each company is active, dissolved or recently incorporated.",
      },
      {
        type: "paragraph",
        content: "Do not stop when the exact spelling is absent. The current [GOV.UK company-name rules](https://www.gov.uk/limited-company-formation/choose-company-name) explain that punctuation, certain special characters and commonly used company-name words may not make a name different. A complaint can also force action when a new name is considered ‘too like’ an earlier registered name.",
      },
      {
        type: "paragraph",
        content: "In the United States there is no single national company-name register. Search the official entity database for the state where you will form the business, then check any state, county or city office responsible for a DBA or assumed name. The [US Small Business Administration’s name guide](https://www.sba.gov/business-guide/launch-your-business/choose-your-business-name) confirms that entity-name and DBA requirements vary by location and are legally separate from federal trade marks.",
      },
      {
        type: "callout",
        calloutType: "tip",
        content: "A company register accepting a name is not trade mark clearance. It answers an incorporation question, not whether customers could confuse your brand with someone else’s.",
      },
      { type: "heading", level: 2, content: "Database 2: The UK IPO Trade Marks Register" },
      {
        type: "paragraph",
        content: "Use the official [UK Intellectual Property Office search](https://www.gov.uk/search-for-trademark) for any brand that will trade in the UK. Run the exact phrase, each distinctive word, shortened forms and likely phonetic variants. Review both applications and registrations rather than looking only for an identical registered word mark.",
      },
      {
        type: "paragraph",
        content: "For each close result, read the goods and services specification, owner, filing date and status. The UKIPO advises applicants to search for the same or similar marks and to identify the relevant classes and terms before applying. Its [before-you-apply guidance](https://www.gov.uk/how-to-register-a-trade-mark/before-you-apply) also recommends professional advice when you find a similar mark.",
      },
      { type: "heading", level: 2, content: "Database 3: The USPTO Federal Trademark Database" },
      {
        type: "paragraph",
        content: "For the United States, use the official [USPTO Trademark Search system](https://tmsearch.uspto.gov/). Begin with the exact wording, then expand to shared terms, alternative spellings, similar pronunciations and the strongest word in a multi-word name. Search each serious candidate consistently so a favourite name does not receive a less rigorous review.",
      },
      {
        type: "paragraph",
        content: "The USPTO’s [federal trademark searching guidance](https://www.uspto.gov/trademarks/search/federal-trademark-searching) says that marks may conflict when they are confusingly similar and their goods or services are related. Similarity can arise from appearance, sound, meaning or overall commercial impression. Related goods do not have to sit in the same international class.",
      },
      { type: "heading", level: 2, content: "Database 4: EUIPO TMview" },
      {
        type: "paragraph",
        content: "If the European Union is a current or planned market, use [EUIPO’s TMview guidance](https://www.euipo.europa.eu/en/trade-marks/before-applying/availability) and open TMview from the official page. EUIPO states that TMview contains applications and registrations from EU national intellectual-property offices, EUIPO and many participating offices outside the EU.",
      },
      {
        type: "paragraph",
        content: "Repeat the same exact, partial and phonetic searches used for the UK and US. Filter by territory and status only after a broad first pass, then inspect similar signs with similar goods or services. For an EU-wide launch, also consider translations, obvious local spellings and how the name is likely to be pronounced in priority markets. The [international brand-name checklist](/blog/international-brand-name-checks) covers the linguistic checks that sit outside registry data.",
      },
      { type: "heading", level: 2, content: "Use This Result Log" },
      {
        type: "table",
        content: "",
        headers: ["Field", "What to record", "Why it matters"],
        rows: [
          ["Search query", "Exact term or variant entered", "Proves the scope of the screen"],
          ["Record", "Owner, application number and status", "Lets you reopen and verify the result"],
          ["Market", "UK, US state, US federal or EU", "Rights are territorial"],
          ["Goods/services", "Relevant wording, not just class number", "Shows whether commercial activity may overlap"],
          ["Similarity", "Look, sound, meaning and overall impression", "Captures more than exact spelling"],
          ["Decision", "Green, amber or red with one-sentence reason", "Makes the shortlist comparable"],
        ],
      },
      { type: "heading", level: 2, content: "The Clearance Decision Tree" },
      {
        type: "list",
        content: "",
        items: [
          "Exact legal-entity name unavailable in the place you must register → change the legal name or investigate the jurisdiction’s rules before filing.",
          "Live or pending similar trade mark plus related goods or services → stop and obtain professional advice before investing in the name.",
          "Similar mark but the commercial relationship is unclear → mark amber; compare customers, sales channels, purpose and realistic expansion.",
          "Only dead or inactive records appear → investigate whether the name is still used in commerce; do not treat the record as an automatic green light.",
          "No material registry conflicts after exact and variant searches → provisional green; continue with web, domain, social-handle and professional checks.",
        ],
      },
      {
        type: "paragraph",
        content: "A green result means ‘no obvious conflict found in this preliminary screen’, not ‘legally cleared’. An amber result means the answer depends on facts that a database cannot decide. A red result means the cost of changing direction now is likely lower than building around an unresolved conflict.",
      },
      { type: "heading", level: 2, content: "What to Check After the Four Databases" },
      {
        type: "paragraph",
        content: "Official registers do not contain every trading name or unregistered right. Search the open web, business directories, app stores and relevant marketplaces for active businesses using the exact name or close variants. Then check the matching domain and its history. Our guide to [choosing a domain name](/blog/how-to-choose-a-domain-name) explains the brand and usability tests that follow legal screening.",
      },
      {
        type: "paragraph",
        content: "Finally, reserve the domain and priority handles only after the shortlist survives the clearance screen. Use the [brand protection checklist](/blog/secure-brand-across-platforms) to secure the remaining surfaces without confusing ownership of a URL or social account with ownership of trade mark rights.",
      },
      { type: "heading", level: 2, content: "A Repeatable Final Checklist" },
      {
        type: "list",
        content: "",
        items: [
          "Define the exact name, variants, territories and goods or services",
          "Search the relevant official company or state entity register",
          "Search UKIPO for exact, partial and phonetic matches",
          "Search USPTO for similar marks and related goods or services",
          "Search EUIPO TMview for EU and national-office records",
          "Log owners, statuses, filing details and commercial overlap",
          "Escalate every red result and unresolved amber result",
          "Check unregistered use, domains and social handles",
          "Re-run all searches immediately before filing or launch",
        ],
      },
      {
        type: "buttonCta",
        content: "Build a stronger shortlist before you begin the four-database clearance workflow.",
        ctaLink: "/generate",
        ctaText: "Generate business names",
      },
      {
        type: "links",
        content: "Continue your naming workflow",
        links: [
          { text: "How to Choose a Domain Name", href: "/blog/how-to-choose-a-domain-name" },
          { text: "Secure Your Brand Across Every Platform", href: "/blog/secure-brand-across-platforms" },
        ],
      },
    ],
    faqs: [
      {
        question: "Does Companies House approval mean a business name is legally safe?",
        answer: "No. Companies House determines whether a company name meets its registration rules. It does not provide a trade mark clearance opinion. Search the UKIPO register separately and investigate unregistered use before committing.",
      },
      {
        question: "Can two businesses use the same name in different industries?",
        answer: "Sometimes, but industry labels alone do not decide the issue. The relevant questions include how similar the names are, whether the goods or services are related, who the customers are and whether the public could believe both offers come from the same source. Get professional advice when the overlap is unclear.",
      },
      {
        question: "Do I need to search UK, US and EU trade mark databases?",
        answer: "Search every territory where you currently trade or have a realistic launch plan. An online-first company expecting customers across the UK, United States and European Union should investigate all three. A strictly local business may have a narrower initial scope, but expansion should trigger a fresh search.",
      },
      {
        question: "Is a dead or expired trade mark safe to use?",
        answer: "Not automatically. A dead register record cannot be treated like a live federal registration, but the owner or another business may still be using the name and may hold other rights. Investigate current commercial use and seek advice if the activity overlaps with yours.",
      },
      {
        question: "Does an available domain mean the business name is available?",
        answer: "No. Domain registration, legal-entity registration and trade mark rights are separate. A domain can be unregistered even when another business owns relevant rights in the name.",
      },
      {
        question: "When should I hire a trade mark attorney?",
        answer: "Get professional help when a search finds a similar live or pending mark, when related goods or services are difficult to assess, when you plan a multi-country launch, or before committing significant money to packaging, advertising, development or a trade mark application. This preliminary workflow is not legal advice.",
      },
    ],
  },
  {
    slug: "business-name-vs-legal-company-name-vs-dba",
    title: "Business Name vs Legal Company Name vs Trading Name/DBA",
    description: "Understand which name belongs on contracts, customer-facing materials and registrations—and when a trading name or DBA is useful.",
    seoTitle: "Business Name vs Legal Name vs DBA: Key Differences",
    metaDescription: "Learn how legal company names, trading names and DBAs differ in the UK and US, what each registration does, and which checks to run before launch.",
    category: "Domain Strategy",
    readTime: 8,
    publishedAt: "2026-07-11",
    updatedAt: "2026-07-11",
    author: "Andrew Barrett",
    qualityTier: "priority",
    primaryKeyword: "business name vs legal name vs DBA",
    searchIntent: "informational",
    pillar: "Name Clearance & IP",
    tags: ["legal company name", "trading name", "DBA", "business name", "trademark"],
    relatedSlugs: [
      "how-to-choose-a-domain-name",
      "secure-brand-across-platforms",
      "startup-domain-naming-strategy-framework",
      "domain-validation-checklist",
    ],
    sources: [
      {
        title: "Choose your business name",
        url: "https://www.sba.gov/business-guide/launch-your-business/choose-your-business-name",
        authority: "U.S. Small Business Administration",
        lastVerified: "2026-07-11",
      },
      {
        title: "Choose a company name",
        url: "https://www.gov.uk/limited-company-formation/choose-company-name",
        authority: "Companies House / GOV.UK",
        lastVerified: "2026-07-11",
      },
      {
        title: "Naming your business",
        url: "https://www.business.gov.uk/support/business-ideas-planning-and-naming/naming-your-business/",
        authority: "UK Government Business Service",
        lastVerified: "2026-07-11",
      },
      {
        title: "How trademarks and trade names differ",
        url: "https://www.uspto.gov/sites/default/files/documents/TM-Trademark-or-Trade-Name-flyer.pdf",
        authority: "United States Patent and Trademark Office",
        lastVerified: "2026-07-11",
      },
      {
        title: "Likelihood of confusion",
        url: "https://www.uspto.gov/trademarks/search/likelihood-confusion",
        authority: "United States Patent and Trademark Office",
        lastVerified: "2026-07-11",
      },
    ],
    content: [
      {
        type: "paragraph",
        content: "A founder can say ‘our business name’ and mean four different things: the name of the legal entity, the name customers see, a trademark, or the domain. Those layers often match, but they do not have to. Confusing them creates practical problems: contracts signed under an unidentified brand, a DBA mistaken for trademark protection, or a company registration treated as permission to use a name nationally.",
      },
      {
        type: "callout",
        calloutType: "warning",
        content: "This guide is general information, not legal advice. Naming, disclosure and registration rules vary by country, US state, locality, industry and business structure. Check the current official rules where you operate and use a qualified lawyer or trade mark attorney for material risk.",
      },
      { type: "heading", level: 2, content: "The Four Name Layers at a Glance" },
      {
        type: "table",
        content: "",
        headers: ["Name layer", "What it identifies", "Where it appears", "What registration does"],
        rows: [
          ["Legal company or entity name", "The person or entity carrying the legal obligations", "Formation records, tax, banking, contracts and invoices", "Records the entity under the rules of the forming jurisdiction"],
          ["Trading name or DBA", "The public-facing alias used by that person or entity", "Website, shopfront, proposals, product marketing and receipts", "May satisfy a local filing or disclosure rule; does not create a separate entity"],
          ["Trademark", "The source of particular goods or services", "Brand, logo, packaging, software and advertising", "Can create or strengthen rights for the mark in connection with specified goods or services"],
          ["Domain name", "An internet address", "Website and email", "Gives control of that registration while it remains active; it does not itself grant trademark rights"],
        ],
      },
      {
        type: "paragraph",
        content: "The US Small Business Administration treats entity names, trademarks, DBAs and domains as independent registrations serving different purposes. A result in one database does not answer every naming question.",
      },
      { type: "heading", level: 2, content: "1. The Legal Company or Entity Name" },
      {
        type: "paragraph",
        content: "The legal name identifies the party that owns assets, owes money, employs people and signs agreements. For a UK limited company, it is the name registered at Companies House. For a US corporation or LLC, it is generally the entity name accepted by the relevant state. A sole trader may instead operate legally in the individual’s own name, subject to local rules.",
      },
      {
        type: "list",
        content: "Use the legal name where the counterparty needs to know who it is dealing with:",
        items: [
          "Formation, tax and regulatory filings",
          "Banking, payment processor and insurance records",
          "Employment, supplier, customer and investment agreements",
          "Invoices, legal notices and required website disclosures",
          "Applications for licences, credit or public procurement",
        ],
      },
      {
        type: "paragraph",
        content: "Entity-name acceptance is not full brand clearance. Companies House warns that a UK name may still have to change after a complaint if it is too like an earlier company name or trade mark. In the US, formation rules differ by state, while federal trademark questions are handled separately. Treat incorporation as one administrative check, not a universal right to use the wording.",
      },
      { type: "heading", level: 2, content: "2. The Trading Name or DBA" },
      {
        type: "paragraph",
        content: "A trading name is the label used in public when it differs from the legal name. In US guidance it is commonly called a ‘doing business as’ name, assumed name or fictitious name. In the UK, Companies House calls a different trading identity a business name. The alias may make a long legal name easier to market, let a sole trader avoid branding around a personal name, or let one company operate more than one customer proposition.",
      },
      {
        type: "paragraph",
        content: "Suppose Northstar Systems Ltd launches a bookkeeping product called BrightLedger. Northstar Systems Ltd remains the contracting entity; BrightLedger can be the customer-facing trading and product name. A clear footer or invoice might say ‘BrightLedger is a trading name of Northstar Systems Ltd’. The wording does not create a second company. It tells the customer which legal entity stands behind the brand.",
      },
      {
        type: "table",
        content: "",
        headers: ["Question", "United Kingdom", "United States"],
        rows: [
          ["Is there one central DBA filing?", "No equivalent universal filing. Companies may trade under another business name, subject to name and disclosure rules.", "No single national DBA filing. Requirements can sit at state, county or city level."],
          ["Does the alias create a new entity?", "No", "No"],
          ["Does filing the alias create trademark protection?", "No; trade mark rights and registration are separate", "The SBA says DBA registration does not itself provide legal protection"],
          ["Can restricted wording apply?", "Yes. Certain company-type terms and sensitive words are restricted", "Rules and required suffixes vary by state and structure"],
        ],
      },
      {
        type: "paragraph",
        content: "A DBA is useful administration, not a clearance certificate. It does not prove the name is free of confusingly similar marks, reserve every domain, or remove the need to identify the legal entity on documents where disclosure is required.",
      },
      { type: "heading", level: 2, content: "3. The Trademark Layer" },
      {
        type: "paragraph",
        content: "A trademark is not simply another record of the company name. It identifies the source of goods or services. A legal name, trading name or product name can also function as a trademark when customers encounter it in that source-identifying way. Conversely, merely forming an entity or owning a domain does not automatically settle the trademark question.",
      },
      {
        type: "paragraph",
        content: "The USPTO assesses more than exact matches. Marks can conflict because they are similar in sound, appearance, meaning or commercial impression, combined with related goods or services. That is why searching only the exact spelling creates false confidence. Run spelling, phonetic and conceptual variants, then inspect what each owner actually sells.",
      },
      {
        type: "callout",
        calloutType: "tip",
        content: "Keep the tests separate: entity availability asks whether a registry will accept the legal name; trademark clearance asks whether marketplace use may conflict with earlier rights. Passing one does not mean passing the other.",
      },
      { type: "heading", level: 2, content: "A Practical Decision Tree" },
      {
        type: "list",
        content: "Work through these questions in order:",
        items: [
          "Who will sign contracts and receive revenue? Give that person or entity a compliant legal name.",
          "Will customers see a shorter or different name? Check whether a trading-name or DBA filing and specific disclosures are required locally.",
          "Will the public use that wording to identify your goods or services? Run a proper trademark clearance search and decide whether professional advice or an application is warranted.",
          "Will the name lead your website and email? Check the domain separately; registration does not cure a company-name or trademark conflict.",
          "Will more than one product sit under the entity? Record which names belong to the company, each product and each jurisdiction before launch.",
        ],
      },
      { type: "heading", level: 2, content: "Three Common Structures" },
      {
        type: "table",
        content: "",
        headers: ["Structure", "Example", "Best fit", "Main risk"],
        rows: [
          ["One name everywhere", "BrightLedger Ltd trading as BrightLedger at brightledger.com", "A focused company with one main offer", "A conflict affects the whole identity at once"],
          ["Neutral legal name plus trading brand", "Northstar Systems Ltd trading as BrightLedger", "Founders who want corporate flexibility behind one public brand", "Customers may be confused unless the relationship is disclosed clearly"],
          ["One entity, several brands", "Northstar Systems Ltd operating BrightLedger and InvoicePilot", "A portfolio with genuinely different products or audiences", "Every extra brand adds search, trademark, domain and marketing work"],
        ],
      },
      {
        type: "paragraph",
        content: "For most single-product startups, matching the legal, trading and primary product name is simpler. It reduces explanation, domain sprawl and duplicated brand work. Use a separate legal name only when there is a real reason, not because a vague holding-company label sounds more sophisticated.",
      },
      { type: "heading", level: 2, content: "The Name-Setup Workflow" },
      {
        type: "paragraph",
        content: "Start with a shortlist created for the actual audience and category. [Choose a domain-name structure](/blog/how-to-choose-a-domain-name), then [generate additional candidates](/generate) if the strongest option fails a check. [Founder Signal](/founder-signal) can help compare brand characteristics, but scoring is not legal clearance.",
      },
      {
        type: "list",
        content: "For each finalist:",
        items: [
          "Write the legal form, public brand and intended product names exactly, including suffixes.",
          "Search the relevant company or entity registry for exact and close variants.",
          "Search official trademark databases for spelling, sound and meaning variants in related goods and services.",
          "Search the wider market: web results, app stores, sector directories and social platforms.",
          "Use the [bulk domain checker](/bulk-domain-check) for supported extensions, then re-confirm at the registrar before purchase.",
          "Record the search date, databases, queries, close results and the reason you accepted or rejected the name.",
          "Complete the [cross-platform brand checklist](/blog/secure-brand-across-platforms) before announcing the name.",
        ],
      },
      { type: "heading", level: 2, content: "Show the Relationship Clearly" },
      {
        type: "paragraph",
        content: "A polished trading brand should not hide the contracting party. Put the public name in the headline and the legal identity where people reasonably expect it: website footer, terms, privacy notice, order flow, invoices and contracts. In the UK, official Business.gov.uk guidance states that the legal name must appear on business paperwork so customers and suppliers know who they are dealing with. Exact requirements vary, so verify the current rule for your structure and location.",
      },
      { type: "heading", level: 2, content: "Pre-Launch Checklist" },
      {
        type: "list",
        content: "",
        items: [
          "Legal entity name accepted in the forming jurisdiction",
          "Trading-name or DBA requirements checked for every operating location",
          "Restricted words and required legal suffixes checked",
          "Trademark searches cover variants and related goods or services",
          "Domain and core handles confirmed separately",
          "Contracts, invoices, policies and footer identify the legal party",
          "Ownership of domains and brand assets sits with the correct person or entity",
          "Search evidence saved and high-risk results reviewed professionally",
        ],
      },
      {
        type: "links",
        content: "Official sources — last reviewed 11 July 2026",
        links: [
          { text: "US SBA: Choose your business name", href: "https://www.sba.gov/business-guide/launch-your-business/choose-your-business-name" },
          { text: "Companies House: Choose a company name", href: "https://www.gov.uk/limited-company-formation/choose-company-name" },
          { text: "Business.gov.uk: Naming your business", href: "https://www.business.gov.uk/support/business-ideas-planning-and-naming/naming-your-business/" },
          { text: "USPTO: How trademarks and trade names differ", href: "https://www.uspto.gov/sites/default/files/documents/TM-Trademark-or-Trade-Name-flyer.pdf" },
          { text: "USPTO: Likelihood of confusion", href: "https://www.uspto.gov/trademarks/search/likelihood-confusion" },
        ],
      },
      { type: "heading", level: 2, content: "The Bottom Line" },
      {
        type: "paragraph",
        content: "Your legal company name answers ‘who is responsible?’, a trading name or DBA answers ‘what do customers call us?’, and a trademark answers ‘what identifies the source of these goods or services?’. A domain answers none of those legal questions; it is the address people use to reach you. Keep the layers aligned where possible, document the differences where necessary, and clear each one through the system designed for it.",
      },
    ],
    faqs: [
      {
        question: "Can my trading name be different from my limited company name?",
        answer: "Yes. UK companies can trade under a different business name, subject to restrictions and disclosure rules. The company remains the legal party. Check sensitive-word restrictions, trade mark conflicts and the current requirements for displaying the registered company name.",
      },
      {
        question: "Does registering a DBA create a company?",
        answer: "No. A DBA is an alias used by an existing person or entity. US filing requirements vary by state, county and city, and the SBA notes that registering a DBA does not itself provide legal protection. It does not replace entity formation or trademark clearance.",
      },
      {
        question: "Does Companies House registration give me trademark rights?",
        answer: "Do not assume so. Company-name registration and trade mark protection are separate. Companies House itself recommends searching the UK Intellectual Property Office register, and a company may have to change a name after a successful complaint.",
      },
      {
        question: "Which name should appear on an invoice or contract?",
        answer: "The legal party must be identifiable. A trading brand can be prominent, but the document should also show the registered entity or individual behind it and any other information required by local law. Use wording such as ‘Brand is a trading name of Legal Entity Ltd’ where appropriate.",
      },
      {
        question: "Can one company own several trading or product names?",
        answer: "Often yes, but every additional name creates another clearance, domain, trademark, disclosure and brand-management task. It also does not create separate liability by itself. Confirm local filing rules and make the parent entity clear to customers and counterparties.",
      },
    ],
  },
  {
    slug: "company-name-vs-product-name-brand-architecture",
    title: "Company Name vs Product Name: A Startup Brand Architecture Guide",
    description: "Decide whether your company and product should share one name, use an endorsed relationship, or become separate brands.",
    seoTitle: "Company Name vs Product Name: Brand Architecture Guide",
    metaDescription: "Decide whether your startup and product should share one name or use separate brands with this practical architecture framework, checklist and examples.",
    category: "Builder Insights",
    readTime: 8,
    publishedAt: "2026-07-11",
    updatedAt: "2026-07-11",
    author: "Andrew Barrett",
    qualityTier: "priority",
    primaryKeyword: "company name vs product name",
    searchIntent: "informational",
    pillar: "Naming Strategy",
    tags: ["company name", "product name", "brand architecture", "sub-brand", "startup naming"],
    relatedSlugs: [
      "how-to-name-saas-product",
      "naming-b2b-vs-b2c-startups",
      "startup-rebrand-playbook",
      "secure-brand-across-platforms",
    ],
    sources: [
      {
        title: "How trademarks and trade names differ",
        url: "https://www.uspto.gov/sites/default/files/documents/TM-Trademark-or-Trade-Name-flyer.pdf",
        authority: "United States Patent and Trademark Office",
        lastVerified: "2026-07-11",
      },
      {
        title: "Goods and services",
        url: "https://www.uspto.gov/trademarks/basics/goods-and-services",
        authority: "United States Patent and Trademark Office",
        lastVerified: "2026-07-11",
      },
      {
        title: "Likelihood of confusion",
        url: "https://www.uspto.gov/trademarks/search/likelihood-confusion",
        authority: "United States Patent and Trademark Office",
        lastVerified: "2026-07-11",
      },
      {
        title: "Goods and services",
        url: "https://www.euipo.europa.eu/en/trade-marks/before-applying/goods-and-services",
        authority: "European Union Intellectual Property Office",
        lastVerified: "2026-07-11",
      },
      {
        title: "Choose your business name",
        url: "https://www.sba.gov/business-guide/launch-your-business/choose-your-business-name",
        authority: "U.S. Small Business Administration",
        lastVerified: "2026-07-11",
      },
    ],
    content: [
      {
        type: "paragraph",
        content: "Should the startup and its product have the same name? For a founder with one product, the simplest answer is usually yes. The difficult cases begin when the company expects several products, serves sharply different audiences, acquires an existing brand, or wants a product that could one day stand alone. That is a brand-architecture decision, not just a naming exercise.",
      },
      {
        type: "paragraph",
        content: "The company name identifies the organisation behind the work. A product name identifies a specific offer customers buy or use. Brand architecture defines how those names relate in public: one shared identity, a visible parent-and-product relationship, or separate product brands owned by a less visible company.",
      },
      {
        type: "callout",
        calloutType: "warning",
        content: "Brand architecture does not create legal separation. Two product brands operated by one company normally remain offers of that company unless separate entities and agreements say otherwise. Trademark, company-name and disclosure rules are jurisdiction-specific; this article is strategic information, not legal advice.",
      },
      { type: "heading", level: 2, content: "The Three Practical Models" },
      {
        type: "table",
        content: "",
        headers: ["Model", "How names appear", "Best fit", "Cost and risk"],
        rows: [
          ["One shared name", "Company and product use the same core name", "One flagship product, one audience, one reputation", "Lowest complexity; a reputation or naming problem reaches everything"],
          ["Endorsed product or sub-brand", "Product has a name, visibly linked to the parent", "A product needs clarity or personality but benefits from parent trust", "Moderate complexity; the relationship needs consistent wording and design"],
          ["Separate product brands", "Customers mainly see independent product names", "Different markets, acquired brands or products built to stand alone", "Highest cost; each brand needs positioning, clearance, domains and demand"],
        ],
      },
      { type: "heading", level: 2, content: "Model 1: One Shared Name" },
      {
        type: "paragraph",
        content: "A shared name is the default for an early-stage, single-product company. If the legal entity is LumaDesk Ltd, the product is LumaDesk, and the main domain is lumadesk.com, every mention reinforces the same memory. Sales does not explain a parent company. Support, social proof and search demand accumulate around one label. Design and trademark work are concentrated rather than duplicated.",
      },
      {
        type: "list",
        content: "Choose one shared name when:",
        items: [
          "The product is the company’s main reason to exist",
          "The company and product serve the same buyer and user",
          "The roadmap is expansion within one recognisable platform",
          "Trust in the company should transfer directly to every feature",
          "There is no credible need to sell, spin out or retire the product independently",
        ],
      },
      { type: "heading", level: 2, content: "Model 2: An Endorsed Product" },
      {
        type: "paragraph",
        content: "An endorsed structure gives the product its own memorable label while keeping the parent visible: ‘Relay by Northstar’, ‘Northstar Relay’, or ‘Relay, from Northstar’. It works when the product needs a clearer promise than the broad company name can carry, but parent trust still helps conversion.",
      },
      {
        type: "list",
        content: "Use endorsement when:",
        items: [
          "The parent already has credibility with the target buyer",
          "The product has a distinct job without needing a fully independent company story",
          "Several products should feel related but not interchangeable",
          "You want a naming system that can extend: Northstar Relay, Northstar Signal, Northstar Atlas",
          "Customers need to know which company provides support, security and contracts",
        ],
      },
      { type: "heading", level: 2, content: "Model 3: Separate Product Brands" },
      {
        type: "paragraph",
        content: "A house of separate product brands can be right when the audiences, categories and promises are genuinely different. A workflow tool for hospital teams and a consumer journalling app may not benefit from sharing a name, tone or distribution channel. Acquired products may also retain valuable recognition that a forced rename would destroy.",
      },
      {
        type: "paragraph",
        content: "This model is expensive. Every product needs a distinct position, name search, trademark assessment, domain plan, visual system, launch story, analytics taxonomy and ongoing maintenance. The parent cannot assume its reputation will automatically transfer. Early-stage teams often underestimate that multiplication.",
      },
      {
        type: "callout",
        calloutType: "tip",
        content: "Separate brands because the market requires separation, not because the team enjoys naming things. One strong brand with several clearly labelled features is usually easier to build than three underfunded brands.",
      },
      { type: "heading", level: 2, content: "The Decision Scorecard" },
      {
        type: "table",
        content: "",
        headers: ["Question", "Shared name points", "Separate product points"],
        rows: [
          ["Buyer and user", "Same people and buying motion", "Different audiences, channels or trust requirements"],
          ["Product promise", "One platform promise covers the roadmap", "Each product solves a different category-level problem"],
          ["Reputation", "Parent credibility helps the product", "Parent associations would confuse or constrain it"],
          ["Portfolio future", "Features deepen one core product", "Products may be sold, acquired or retired independently"],
          ["Team capacity", "One marketing and brand team", "Resources exist to build and maintain each identity"],
          ["Customer clarity", "One name makes the offer easier to explain", "A product name makes selection materially clearer"],
        ],
      },
      { type: "heading", level: 2, content: "A Founder-Friendly Decision Tree" },
      {
        type: "list",
        content: "",
        items: [
          "Do you have only one core product? Use the company name for the product unless a real constraint prevents it.",
          "Will the second offer serve the same buyer under the same promise? Treat it as a feature, plan or module before creating another brand.",
          "Does the product need a distinct label for navigation or sales clarity? Create a descriptive product name or an endorsed sub-brand.",
          "Would sharing the parent name confuse the audience or weaken trust? Consider a separate brand, then budget for separate brand-building.",
          "Could the product be sold or spun out independently? Give it an ownable name and clean ownership records, while keeping the legal relationship clear.",
          "Are you uncertain? Launch with one name and document a trigger for revisiting the choice. Simplicity is reversible; premature brand sprawl is costly.",
        ],
      },
      { type: "heading", level: 2, content: "Four Startup Scenarios" },
      {
        type: "table",
        content: "",
        headers: ["Scenario", "Recommended architecture", "Why"],
        rows: [
          ["A solo team building one SaaS analytics product", "One shared name", "One audience and one reputation; the product is the company"],
          ["A developer platform adding a monitoring module", "Parent plus descriptive module", "The module benefits from platform trust and does not need independent demand"],
          ["A B2B company launching a consumer app", "Endorsed or separate product", "Tone, channel and trust signals differ enough to justify a distinct customer identity"],
          ["A studio operating three unrelated acquired apps", "Separate product brands with a clear owner", "Existing recognition is valuable and the products may have independent futures"],
        ],
      },
      { type: "heading", level: 2, content: "Name Each Layer for Its Job" },
      {
        type: "paragraph",
        content: "A company name must survive the broadest plausible strategy. Score it for longevity, pronunciation, credibility and the ability to sit above future offers. A product name can be more specific: it should make the product easy to recall, recommend and distinguish inside its category. The [SaaS product naming framework](/blog/how-to-name-saas-product) covers that narrower decision, while the [B2B versus B2C guide](/blog/naming-b2b-vs-b2c-startups) helps calibrate tone to the buyer.",
      },
      {
        type: "paragraph",
        content: "If you need candidates, [generate names from the actual brief](/generate), not from an abstract desire to sound innovative. Compare the finalists with [Founder Signal](/founder-signal), then say the full architecture aloud: ‘Northstar makes Relay’, ‘Relay by Northstar’, and ‘We use Relay’. The relationship should be explainable in one breath.",
      },
      { type: "heading", level: 2, content: "Clear Every Customer-Facing Name" },
      {
        type: "paragraph",
        content: "A separate product name is not lower-risk because it is not the company name. The USPTO explains that a trade name and a trademark can overlap depending on how the wording is used, and that a trademark identifies the source of goods or services. Its conflict analysis considers similarity plus whether the goods or services are related. EUIPO likewise states that trade mark protection attaches to the specified goods and services.",
      },
      {
        type: "list",
        content: "For the company name and every public product name:",
        items: [
          "Search relevant company and trademark databases, including close sound, spelling and meaning variants",
          "Define the goods or services the public will associate with the name",
          "Check the supported domains together with the [bulk domain checker](/bulk-domain-check), then confirm at the registrar",
          "Check app stores, major directories, social platforms and ordinary web use",
          "Record who owns the name, domain, design files and any applications",
          "Escalate close results or important launches to a qualified professional",
        ],
      },
      { type: "heading", level: 2, content: "Match the Domain Architecture" },
      {
        type: "paragraph",
        content: "Use one main domain when the company and product share a brand. Put modules in clear paths rather than buying a domain for every feature. An endorsed product can live in a parent-domain section while it proves demand. Give a separate product its own domain only when it truly has an independent audience, message and acquisition plan. Domain separation should follow business separation, not cause it.",
      },
      { type: "heading", level: 2, content: "Document the System Before Launch" },
      {
        type: "list",
        content: "A one-page architecture note should state:",
        items: [
          "The exact legal entity name and public company name",
          "Each product, module and plan name, with its role",
          "The approved parent-product lockup and sentence describing ownership",
          "Which name leads on the website, product UI, app store, contracts and support",
          "The primary domain and redirect ownership for each public brand",
          "Who can create another product name and what evidence must justify it",
          "The trigger for merging, endorsing or separating a product later",
        ],
      },
      {
        type: "paragraph",
        content: "If the architecture must change, treat it as a migration rather than a copy edit. Inventory URLs and customer touchpoints, preserve redirects, explain the relationship, and follow the [startup rebrand playbook](/blog/startup-rebrand-playbook) before switching names in public.",
      },
      {
        type: "links",
        content: "Official sources — last reviewed 11 July 2026",
        links: [
          { text: "USPTO: How trademarks and trade names differ", href: "https://www.uspto.gov/sites/default/files/documents/TM-Trademark-or-Trade-Name-flyer.pdf" },
          { text: "USPTO: Goods and services", href: "https://www.uspto.gov/trademarks/basics/goods-and-services" },
          { text: "USPTO: Likelihood of confusion", href: "https://www.uspto.gov/trademarks/search/likelihood-confusion" },
          { text: "EUIPO: Goods and services", href: "https://www.euipo.europa.eu/en/trade-marks/before-applying/goods-and-services" },
          { text: "US SBA: Choose your business name", href: "https://www.sba.gov/business-guide/launch-your-business/choose-your-business-name" },
        ],
      },
      { type: "heading", level: 2, content: "The Bottom Line" },
      {
        type: "paragraph",
        content: "Start with one name when the company and product tell one story. Add an endorsed product when customers need a distinct label but parent trust still matters. Create a separate brand only when the audience, proposition and future are independent enough to repay the extra work. The best architecture is not the one with the most names; it is the one customers understand fastest and the team can support consistently.",
      },
    ],
    faqs: [
      {
        question: "Should a startup and its first product have the same name?",
        answer: "Usually yes. When one product is the company’s main reason to exist, a shared name concentrates memory, trust, domain authority and marketing effort. Split the names only when there is a specific strategic, audience or ownership reason.",
      },
      {
        question: "Does every product need its own domain?",
        answer: "No. Features, modules and endorsed products can normally live on the main company domain. A separate domain makes sense when the product has an independent audience, positioning and acquisition plan. Confirm availability before committing, but do not let an attractive spare domain dictate the architecture.",
      },
      {
        question: "Do company and product names need separate trademark searches?",
        answer: "Search every name customers will encounter as a source of goods or services. A legal company name and product mark can create different questions, but neither should be assumed safe because the other passed a registry search. Similarity and related goods or services matter, not only exact spelling.",
      },
      {
        question: "When should a product become its own brand?",
        answer: "Consider separation when it serves a different buyer, competes in a different category, needs a distinct trust profile, or may be sold or spun out. Make sure the team can fund the additional positioning, design, clearance, domain and ongoing marketing work.",
      },
      {
        question: "Can we rename or separate the product later?",
        answer: "Yes, and that is often safer than over-designing the architecture at launch. Keep ownership and naming records clean, watch for the decision triggers, and run a deliberate migration with customer communication, URL mapping and redirects when separation becomes justified.",
      },
    ],
  },
]
