import {
  FREE_ADVANCED_GENERATION_LIMIT,
  FREE_FOUNDER_SIGNAL_BATCH_LIMIT,
  FREE_MONTHLY_BULK_CHECK_LIMIT,
  FREE_NAME_SPRINT_DAILY_LIMIT,
  PLAN_CONFIG,
  PRO_FOUNDER_SIGNAL_BATCH_LIMIT,
  PRO_MONTHLY_BULK_CHECK_LIMIT,
  PRO_NAME_SPRINT_MONTHLY_LIMIT,
  PRO_ANNUAL_PRICE_GBP,
  PRO_MONTHLY_PRICE_GBP,
} from "@/lib/plans"

export const PRODUCT_OFFER = {
  freeTokenLimit: FREE_MONTHLY_BULK_CHECK_LIMIT,
  freeMonthlyUses: FREE_MONTHLY_BULK_CHECK_LIMIT,
  freeAdvancedBatches: FREE_ADVANCED_GENERATION_LIMIT,
  freeFounderSignalBatches: FREE_FOUNDER_SIGNAL_BATCH_LIMIT,
  freeNameSprintDailyRuns: FREE_NAME_SPRINT_DAILY_LIMIT,
  freePlanName: PLAN_CONFIG.free.name,
  freeUsageLabel: `${FREE_MONTHLY_BULK_CHECK_LIMIT} Bulk Check runs per month; Founder Signal is available with Pro`,
  freeQuickUsageLabel: `${FREE_NAME_SPRINT_DAILY_LIMIT} curated Name Sprint per UTC day after sign-in`,
  freeAdvancedUsageLabel: `${FREE_NAME_SPRINT_DAILY_LIMIT} curated Name Sprint per UTC day after sign-in`,
  freeFounderSignalUsageLabel: "Founder Signal is available with Pro",
  paidPlanName: PLAN_CONFIG.pro.name,
  paidPrice: PLAN_CONFIG.pro.price,
  paidPriceLabel: `${PLAN_CONFIG.pro.price}/month`,
  paidAnnualPrice: `£${PRO_ANNUAL_PRICE_GBP}`,
  paidAnnualPriceLabel: `£${PRO_ANNUAL_PRICE_GBP}/year`,
  paidBillingLabel: PLAN_CONFIG.pro.billingLabel,
  paidCheckoutHref: "/api/stripe/checkout",
  proPlanName: PLAN_CONFIG.pro.name,
  proPrice: PLAN_CONFIG.pro.price,
  proMonthlyPrice: PLAN_CONFIG.pro.price.replace("£", ""),
  proAnnualPrice: String(PRO_ANNUAL_PRICE_GBP),
  proPriceLabel: `${PLAN_CONFIG.pro.price}/month`,
  proBillingLabel: PLAN_CONFIG.pro.billingLabel,
  proCtaLabel: "Choose Pro",
  proCtaWithPrice: `Choose ${PLAN_CONFIG.pro.price}/month or £${PRO_ANNUAL_PRICE_GBP}/year`,
  proBulkCheckRuns: PRO_MONTHLY_BULK_CHECK_LIMIT,
  proFounderSignalRuns: PRO_FOUNDER_SIGNAL_BATCH_LIMIT,
  proNameSprintRuns: PRO_NAME_SPRINT_MONTHLY_LIMIT,
  checkoutHref: "/api/stripe/checkout",
  pricingHref: "/pricing",
  trustSignals: [
    `${FREE_MONTHLY_BULK_CHECK_LIMIT} free bulk checks per month`,
    "Up to 50 candidate names per batch",
    "Founder Signal scoring with Pro",
    `${PRO_MONTHLY_BULK_CHECK_LIMIT} Pro Bulk Check runs per month`,
    `${PRO_FOUNDER_SIGNAL_BATCH_LIMIT} Pro Founder Signal runs per month`,
    `${PRO_NAME_SPRINT_MONTHLY_LIMIT} Pro Name Sprints per month`,
    "Live domain availability",
    "Cancel through the billing portal",
    `Save £${(PRO_MONTHLY_PRICE_GBP * 12 - PRO_ANNUAL_PRICE_GBP).toFixed(2)} with annual billing`,
  ],
  caveats: [
    "Domain availability is checked live and should be confirmed with the registrar before purchase.",
    "NamoLux links available candidates to social-profile, company and official trade-mark searches; these checks remain separate from domain availability and legal clearance.",
    "Founder Signal is decision support, not legal or trademark advice.",
    "NamoLux may earn a commission if you register through our partner.",
  ],
  cancellationLabel: "Cancel any time through your billing portal.",
  freeCtaLabel: "Check a shortlist",
  secondaryCtaLabel: "Check a shortlist",
  editorialCtaLabel: "Open Bulk Check",
  freeFeatures: PLAN_CONFIG.free.features,
  paidFeatures: PLAN_CONFIG.pro.features,
  proFeatures: PLAN_CONFIG.pro.features,
  proFullFeatures: PLAN_CONFIG.pro.features,
  tiers: [PLAN_CONFIG.free, PLAN_CONFIG.pro],
} as const

export const FREE_TOKEN_LIMIT = PRODUCT_OFFER.freeTokenLimit
