export interface NameIdea {
  name: string
  meaning: string
  score: number
  domain: string
}

export interface NicheData {
  slug: string
  niche: string
  metaTitle: string
  metaDescription: string
  h1: string
  intro: string
  namingTips: string[]
  names: NameIdea[]
}

export const pseoNiches: NicheData[] = [
  {
    slug: "ai",
    niche: "AI & Machine Learning",
    metaTitle: "150 AI Startup Name Ideas (With Domains) | NamoLux",
    metaDescription: "Browse 150 AI startup name ideas with Founder Signal scores and domain suggestions. Find a brandable name for your artificial intelligence company.",
    h1: "AI Startup Name Ideas: 150 Brandable Names for AI Companies",
    intro: "Naming an AI startup is one of the most competitive naming challenges right now. You want a name that conveys intelligence and innovation without sounding like every other AI tool launched this year. The best AI startup names balance technical credibility with approachability — they hint at capability without being literal. Below are 150 handpicked AI startup name ideas, scored by Founder Signal™ for brandability and viability.",
    namingTips: [
      "Avoid overused terms like 'smart', 'neural', 'cognit' — they've become generic",
      "Names evoking light, clarity, or vision work well for AI (Lumina, Prism, Vanta)",
      "Consider .ai domains — they're widely accepted and signal your industry instantly",
      "Short invented words score highest for AI brands — aim for 6-9 characters",
    ],
    names: [
      { name: "LuminaAI", meaning: "Evokes intelligence and illumination — light guiding decisions", score: 92, domain: "lumina.ai" },
      { name: "Vantiq", meaning: "From 'vantage' — suggests elevated perspective and foresight", score: 88, domain: "vantiq.com" },
      { name: "Nexlor", meaning: "Invented compound of 'next' and 'lor' (light) — forward-looking AI", score: 85, domain: "nexlor.ai" },
      { name: "Prismind", meaning: "Prism + mind — refracts complex data into clear insight", score: 87, domain: "prismind.com" },
      { name: "Orvai", meaning: "Orbital + AI — suggests vast, orbiting intelligence", score: 82, domain: "orvai.ai" },
      { name: "Clarix", meaning: "From 'clarity' — AI that brings clear answers from complex data", score: 89, domain: "clarix.ai" },
      { name: "Synapt", meaning: "Synapse + apt — neural connections that are perfectly suited", score: 86, domain: "synapt.com" },
      { name: "Veloxis", meaning: "Velocity + Latin suffix — fast, precise AI processing", score: 83, domain: "veloxis.ai" },
      { name: "Mindrift", meaning: "Where minds drift into new possibilities — creative AI", score: 79, domain: "mindrift.com" },
      { name: "Axoniq", meaning: "Axon (neural pathway) — the core signal of intelligent systems", score: 84, domain: "axoniq.ai" },
      { name: "Perceiv", meaning: "Perceive — AI that truly understands context and nuance", score: 88, domain: "perceiv.com" },
      { name: "Corteva", meaning: "Cortex + nova — a new kind of intelligent core", score: 85, domain: "corteva.ai" },
      { name: "Loopix", meaning: "Loop + ix — iterative intelligence that improves in cycles", score: 81, domain: "loopix.ai" },
      { name: "Synara", meaning: "Synergy + ara — harmonious AI that works alongside humans", score: 87, domain: "synara.ai" },
      { name: "Kognit", meaning: "Cognition — the foundation of genuine understanding", score: 84, domain: "kognit.ai" },
      { name: "Datalux", meaning: "Data + lux (light) — illuminating insights from raw data", score: 82, domain: "datalux.com" },
      { name: "Inferix", meaning: "Infer + ix — AI that draws powerful inferences at speed", score: 86, domain: "inferix.ai" },
      { name: "Orbis AI", meaning: "Latin for 'world' — AI with global vision and reach", score: 80, domain: "orbisai.com" },
      { name: "Nuvola", meaning: "Italian for cloud — lightweight, scalable AI intelligence", score: 83, domain: "nuvola.ai" },
      { name: "Thoughtform", meaning: "Where raw thoughts become structured intelligence", score: 78, domain: "thoughtform.ai" },
      { name: "Solvara", meaning: "Solve + ara — an AI built to resolve complex problems elegantly", score: 85, domain: "solvara.ai" },
      { name: "Zenius", meaning: "Zen + genius — calm, reliable AI intelligence", score: 87, domain: "zenius.ai" },
      { name: "Archon AI", meaning: "Archon (Greek ruler) — the commanding intelligence layer", score: 84, domain: "archonai.com" },
      { name: "Pulsar ML", meaning: "Pulsar (high-energy star) — powerful machine learning at scale", score: 82, domain: "pulsarml.com" },
      { name: "Cognify", meaning: "To cognify — to add intelligence to any process", score: 86, domain: "cognify.ai" },
      { name: "Embrix", meaning: "Ember + ix — AI that sparks insight from cold data", score: 81, domain: "embrix.ai" },
      { name: "Spectra AI", meaning: "Full spectrum intelligence — sees across all dimensions of data", score: 88, domain: "spectraai.com" },
      { name: "Lumiq", meaning: "Lumen + IQ — measures and raises the intelligence quotient of systems", score: 85, domain: "lumiq.ai" },
      { name: "Novasynth", meaning: "Nova + synthesis — creating new intelligence from existing knowledge", score: 83, domain: "novasynth.ai" },
      { name: "Calyx AI", meaning: "Calyx (flower base) — the foundational intelligence layer everything grows from", score: 79, domain: "calyxai.com" },
    ],
  },
  {
    slug: "fintech",
    niche: "Fintech & Finance",
    metaTitle: "150 Fintech Startup Name Ideas (With Domains) | NamoLux",
    metaDescription: "Discover 150 fintech startup name ideas with Founder Signal scores and domain suggestions. Find a memorable name for your financial technology company.",
    h1: "Fintech Startup Name Ideas: 150 Names for Finance & Financial Technology Companies",
    intro: "Fintech branding sits at the intersection of trust and innovation. Your name needs to signal financial credibility while feeling modern enough to stand out from legacy institutions. The best fintech names are short, clean, and suggest either speed, security, clarity, or access — often through subtle metaphor rather than obvious finance terminology. Here are 150 fintech startup name ideas with Founder Signal™ scores.",
    namingTips: [
      "Avoid 'bank', 'finance', 'capital' unless you're specifically regulated — they imply liability",
      "Trust signals matter: names that feel clean and precise outperform clever wordplay",
      "Short names with .com or .io extensions work best for fintech credibility",
      "Names evoking flow, clarity, or infrastructure perform strongly in this space",
    ],
    names: [
      { name: "Vaulta", meaning: "Vault + a — secure, elegant financial storage and management", score: 91, domain: "vaulta.com" },
      { name: "Flowr", meaning: "Flow + r — money flowing smoothly between people and businesses", score: 87, domain: "flowr.io" },
      { name: "Kredix", meaning: "Credit + ix — modern credit infrastructure for the digital age", score: 85, domain: "kredix.com" },
      { name: "Paymint", meaning: "Pay + mint — creating fresh, clean payment experiences", score: 82, domain: "paymint.io" },
      { name: "Lendara", meaning: "Lend + ara — lending reimagined with clarity and fairness", score: 88, domain: "lendara.com" },
      { name: "Clearfi", meaning: "Clear + fi (financial) — transparent financial products", score: 89, domain: "clearfi.com" },
      { name: "Nexbank", meaning: "Next + bank — the next evolution of banking infrastructure", score: 84, domain: "nexbank.io" },
      { name: "Truvest", meaning: "True + invest — genuine, transparent investing for everyone", score: 86, domain: "truvest.com" },
      { name: "Fundra", meaning: "Fund + ra (sun) — funding that powers growth and illuminates opportunity", score: 83, domain: "fundra.io" },
      { name: "Zepay", meaning: "Ze + pay — zero-friction, instant payments", score: 87, domain: "zepay.com" },
      { name: "Monixa", meaning: "Money + ix + a — sleek, modern money management", score: 85, domain: "monixa.com" },
      { name: "Liquido", meaning: "Liquid + o — instantly liquid, always accessible money", score: 82, domain: "liquido.io" },
      { name: "Stackr", meaning: "Stack — building wealth methodically, one layer at a time", score: 84, domain: "stackr.com" },
      { name: "Orion Pay", meaning: "Orion (navigator's star) — payment infrastructure that guides commerce", score: 80, domain: "orionpay.com" },
      { name: "Fortiq", meaning: "Fort + iq — intelligent financial fortress, secure and smart", score: 86, domain: "fortiq.com" },
      { name: "Bridgfi", meaning: "Bridge + fi — bridging access to financial services", score: 83, domain: "bridgfi.com" },
      { name: "Lumnex", meaning: "Luminous + nex — bright financial connections and transactions", score: 81, domain: "lumnex.io" },
      { name: "Wealthic", meaning: "Wealth + ic — the science of building personal wealth", score: 85, domain: "wealthic.com" },
      { name: "Swiftfi", meaning: "Swift + fi — fast financial infrastructure for modern business", score: 88, domain: "swiftfi.io" },
      { name: "Pentra", meaning: "Penetrate + a — breaking through financial barriers for access", score: 82, domain: "pentra.com" },
      { name: "Coreum", meaning: "Core + um — the core layer of modern financial systems", score: 84, domain: "coreum.io" },
      { name: "Elevanta", meaning: "Elevate + a — elevating financial outcomes for individuals", score: 86, domain: "elevanta.com" },
      { name: "Cashform", meaning: "Cash + form — shaping the future of cash and digital payments", score: 79, domain: "cashform.io" },
      { name: "Nexifi", meaning: "Next + fi — the next generation of financial infrastructure", score: 87, domain: "nexifi.com" },
      { name: "Aurem", meaning: "Latin for gold — premium, value-preserving financial products", score: 85, domain: "aurem.io" },
      { name: "Trustifi", meaning: "Trust + ify — making financial services trustworthy by design", score: 83, domain: "trustifi.com" },
      { name: "Pivotal Pay", meaning: "Pivotal — the central payment layer your business revolves around", score: 81, domain: "pivotalpay.com" },
      { name: "Solvent", meaning: "Solvent — always liquid, always reliable financial health", score: 84, domain: "solvent.io" },
      { name: "Meridian Fi", meaning: "Meridian — the point where financial flows converge and balance", score: 82, domain: "meridianfi.com" },
      { name: "Strata Fi", meaning: "Strata — layered financial products built for every level", score: 80, domain: "stratafi.com" },
    ],
  },
  {
    slug: "crypto",
    niche: "Crypto & Web3",
    metaTitle: "150 Crypto & Web3 Startup Name Ideas (With Domains) | NamoLux",
    metaDescription: "Find 150 crypto and Web3 startup name ideas with Founder Signal scores and domain suggestions. Discover a bold name for your blockchain or DeFi company.",
    h1: "Crypto & Web3 Startup Name Ideas: 150 Names for Blockchain & DeFi Companies",
    intro: "Web3 naming follows its own rules. Great crypto brand names project decentralisation, ownership, and trust — while still being memorable enough to earn word-of-mouth in a fast-moving space. The best Web3 names feel strong and purposeful: they suggest protocol-level thinking, not just another token. Below are 150 name ideas for crypto, DeFi, NFT, and blockchain startups.",
    namingTips: [
      "Avoid 'chain', 'block', 'token', 'coin' in isolation — they're overused and SEO-crowded",
      ".io and .xyz are widely accepted in crypto — .com still preferred for mainstream trust",
      "Names with Greek or Roman roots convey timelessness and gravity",
      "Protocol-level names (infrastructure, network names) benefit from short, hard-sounding words",
    ],
    names: [
      { name: "Vortex Protocol", meaning: "A self-reinforcing, powerful network of decentralised value", score: 89, domain: "vortexprotocol.io" },
      { name: "Axiom Chain", meaning: "Axiom — self-evident truths encoded on chain", score: 87, domain: "axiomchain.io" },
      { name: "Nexum", meaning: "Latin: connection, bond — a network that binds value securely", score: 84, domain: "nexum.io" },
      { name: "Solara", meaning: "Solar + a — decentralised energy of value, flowing without centre", score: 86, domain: "solara.xyz" },
      { name: "Verity", meaning: "Truth — a platform where on-chain verification means absolute truth", score: 88, domain: "verity.io" },
      { name: "Aether DAO", meaning: "Aether (fifth element) — governance in the upper layer of the web", score: 85, domain: "aetherdao.com" },
      { name: "Kronos Fi", meaning: "Kronos (time) — time-locked, long-horizon decentralised finance", score: 83, domain: "kronosfi.io" },
      { name: "Empyreal", meaning: "Highest heaven — aspirational, elevated blockchain infrastructure", score: 82, domain: "empyreal.io" },
      { name: "Starknode", meaning: "Stark + node — bare, efficient blockchain node infrastructure", score: 84, domain: "starknode.com" },
      { name: "Cryptara", meaning: "Crypto + ara — a new constellation of decentralised assets", score: 86, domain: "cryptara.io" },
      { name: "Nodus", meaning: "Latin: knot, node — the critical point where networks intersect", score: 85, domain: "nodus.io" },
      { name: "Lumios", meaning: "Lumen + ios — light-speed asset transfer on decentralised rails", score: 83, domain: "lumios.io" },
      { name: "Phalanx", meaning: "Ancient formation — a unified, unbreakable decentralised network", score: 87, domain: "phalanx.io" },
      { name: "Tethis", meaning: "Tethys (Greek sea deity) — vast, deep liquidity across DeFi", score: 82, domain: "tethis.io" },
      { name: "Forgefi", meaning: "Forge — where new financial instruments are created on-chain", score: 84, domain: "forgefi.io" },
      { name: "Oblivio", meaning: "Oblivion — permanent, immutable data that cannot be erased", score: 80, domain: "oblivio.xyz" },
      { name: "Auris", meaning: "Latin for gold — a store of enduring, inflation-resistant value", score: 86, domain: "auris.io" },
      { name: "Nexon Chain", meaning: "Next + on — always-on, next-generation blockchain infrastructure", score: 83, domain: "nexonchain.io" },
      { name: "Vaultis", meaning: "Vault + is — secure, institutional-grade asset custody on-chain", score: 85, domain: "vaultis.io" },
      { name: "Helix DAO", meaning: "Helix — a self-organising, spiralling governance structure", score: 82, domain: "helixdao.io" },
      { name: "Praxis", meaning: "Greek: action, practice — blockchain for real-world use cases", score: 88, domain: "praxis.xyz" },
      { name: "Orin Protocol", meaning: "Orin (Hebrew: light) — illuminating transparent, fair networks", score: 81, domain: "orinprotocol.io" },
      { name: "Cerulean", meaning: "Deep sky blue — expansive, clear, decentralised infrastructure", score: 79, domain: "cerulean.io" },
      { name: "Kestrel", meaning: "Fast, precision-hunting bird — agile DeFi protocol", score: 84, domain: "kestrel.io" },
      { name: "Ironledger", meaning: "Iron + ledger — the immovable, trustworthy record of truth", score: 83, domain: "ironledger.com" },
      { name: "Stellaryx", meaning: "Stellar + yx — next-level decentralised stellar network", score: 85, domain: "stellaryx.io" },
      { name: "Verdex", meaning: "Verdant + dex — a green, sustainable decentralised exchange", score: 82, domain: "verdex.io" },
      { name: "Orcus", meaning: "Deep, vast — protocol for deep liquidity and dark pool DeFi", score: 80, domain: "orcus.io" },
      { name: "Zenith DeFi", meaning: "Peak performance — DeFi at its highest form", score: 84, domain: "zenithdefi.io" },
      { name: "Stasis", meaning: "Equilibrium — stable, balanced crypto assets and protocols", score: 81, domain: "stasis.io" },
    ],
  },
  {
    slug: "marketing",
    niche: "Marketing & Creative Agencies",
    metaTitle: "150 Marketing Agency Name Ideas (With Domains) | NamoLux",
    metaDescription: "Browse 150 marketing agency name ideas with Founder Signal scores and domain suggestions. Find a bold, memorable name for your marketing or creative agency.",
    h1: "Marketing Agency Name Ideas: 150 Names for Marketing, Creative & Digital Agencies",
    intro: "A marketing agency's name is itself a demonstration of its brand capabilities. If your name is forgettable, generic, or sounds like every other agency in the directory, clients will wonder why they should trust you to make their brand memorable. The best agency names project a point of view — bold, purposeful, and a little bit bold. Here are 150 name ideas for marketing, digital, and creative agencies.",
    namingTips: [
      "Agency names that suggest a philosophy or outcome outperform those that describe the service",
      "Avoid 'creative', 'digital', 'media', 'solutions' — they're invisible to clients",
      "One strong word is often better than two average ones",
      ".com is standard for agencies — it signals professionalism to B2B clients",
    ],
    names: [
      { name: "Bold Bureau", meaning: "A bureau that does bold work — no hedging, no safe choices", score: 88, domain: "boldbureau.com" },
      { name: "Overt Studio", meaning: "Overt — marketing that doesn't hide, it commands attention", score: 85, domain: "overtstudio.com" },
      { name: "Forefront", meaning: "Always at the forefront of brand and cultural conversation", score: 87, domain: "forefront.co" },
      { name: "Anker", meaning: "Anchor — the stabilising brand layer for fast-growing companies", score: 84, domain: "anker.co" },
      { name: "Pulse Creative", meaning: "The pulse — always on, always in tune with your market", score: 86, domain: "pulsecreative.com" },
      { name: "Narrative", meaning: "Every brand is a story — we tell yours better", score: 89, domain: "narrative.co" },
      { name: "Dispatch", meaning: "Swift, targeted marketing dispatched with precision", score: 83, domain: "dispatch.co" },
      { name: "Apex Collective", meaning: "Peak performance from a collective of marketing minds", score: 82, domain: "apexcollective.com" },
      { name: "Motif Agency", meaning: "The recurring motif of your brand — the thread that ties everything", score: 85, domain: "motifagency.com" },
      { name: "Signal Works", meaning: "Sending the right signals to the right people at the right time", score: 87, domain: "signalworks.com" },
      { name: "Meridian Brand", meaning: "The highest point — branding at peak clarity and impact", score: 84, domain: "meridianbrand.com" },
      { name: "Kindred Studio", meaning: "Finding the audience that truly resonates with your brand", score: 86, domain: "kindredstudio.com" },
      { name: "Anchor & Rise", meaning: "Rooted in strategy, rising in visibility", score: 83, domain: "anchorandrise.com" },
      { name: "Volant", meaning: "Flying, agile — marketing that moves at the speed of culture", score: 85, domain: "volant.co" },
      { name: "Resonance", meaning: "Marketing that resonates — not just reaches", score: 91, domain: "resonance.co" },
      { name: "Nucleus", meaning: "The creative nucleus — the core from which great campaigns radiate", score: 88, domain: "nucleus.co" },
      { name: "Prism Works", meaning: "Taking one brand message and refracting it across all channels", score: 84, domain: "prismworks.com" },
      { name: "Catalyst Co", meaning: "The catalyst that accelerates brand growth", score: 86, domain: "catalystco.com" },
      { name: "Lantern", meaning: "Lighting the path for brands in competitive markets", score: 82, domain: "lantern.co" },
      { name: "Vantage", meaning: "The elevated vantage point your marketing needs", score: 85, domain: "vantage.co" },
      { name: "Foundry", meaning: "Where brands are forged — raw concept into refined identity", score: 87, domain: "foundry.co" },
      { name: "Ember & Co", meaning: "The spark that becomes the flame — growth marketing done right", score: 83, domain: "emberco.com" },
      { name: "Crestline", meaning: "At the crest — marketing that keeps you at the top", score: 82, domain: "crestline.co" },
      { name: "Tableau", meaning: "The complete picture — full-funnel marketing with clarity", score: 84, domain: "tableau.co" },
      { name: "Lodestar", meaning: "The guiding star — brand strategy that orients everything else", score: 86, domain: "lodestar.co" },
      { name: "Fractal", meaning: "Patterns that scale — marketing systems that grow with you", score: 83, domain: "fractal.co" },
      { name: "Manifold", meaning: "Multiple dimensions — omnichannel marketing with one coherent voice", score: 85, domain: "manifold.co" },
      { name: "Keynote Creative", meaning: "The keynote — the central message everything else supports", score: 82, domain: "keynotecreative.com" },
      { name: "Current Agency", meaning: "Always current — real-time brand strategy and execution", score: 84, domain: "currentagency.com" },
      { name: "Elevate Studio", meaning: "Elevated thinking, elevated results — for ambitious brands", score: 81, domain: "elevatestudio.com" },
    ],
  },
  {
    slug: "fitness",
    niche: "Fitness & Wellness",
    metaTitle: "150 Fitness Brand Name Ideas (With Domains) | NamoLux",
    metaDescription: "Discover 150 fitness brand name ideas with Founder Signal scores and domain suggestions. Find the perfect name for your gym, fitness app, or wellness brand.",
    h1: "Fitness Brand Name Ideas: 150 Names for Gyms, Fitness Apps & Wellness Brands",
    intro: "Fitness brands live and die by their energy. Your name needs to feel like it's already working — like movement, momentum, and transformation. The best fitness brand names are short, punchy, and suggest either strength, speed, endurance, or renewal. They need to work on activewear, apps, and gym walls equally. Here are 150 fitness and wellness brand name ideas.",
    namingTips: [
      "Test your name out loud — it needs to sound strong when shouted or whispered in a yoga studio",
      "Single-syllable words project power; multi-syllable names work better for wellness and recovery brands",
      "Avoid 'fit', 'gym', 'health' as standalone names — pair with something unexpected",
      ".com is essential for fitness brands targeting consumer audiences",
    ],
    names: [
      { name: "Apex Form", meaning: "Peak physical form — training at the highest level", score: 87, domain: "apexform.com" },
      { name: "Kinvex", meaning: "Kinetic + vex — dynamic, challenging movement", score: 84, domain: "kinvex.com" },
      { name: "Grindwell", meaning: "The grind that makes you well — hard work as wellness", score: 86, domain: "grindwell.com" },
      { name: "Fervor", meaning: "Intense passion and heat — training with everything you have", score: 88, domain: "fervor.co" },
      { name: "Vitara", meaning: "Vitality + ara — radiating energy and vitality", score: 85, domain: "vitara.co" },
      { name: "Ignite Athletics", meaning: "Igniting potential — performance coaching and training", score: 83, domain: "igniteathletics.com" },
      { name: "Steadfast", meaning: "Unwavering commitment to showing up and doing the work", score: 86, domain: "steadfast.co" },
      { name: "Torq Fitness", meaning: "Torque — rotational force, power generated from your core", score: 84, domain: "torqfitness.com" },
      { name: "Revive Wellness", meaning: "Revive — resetting, restoring, and rebuilding your best self", score: 87, domain: "revivewellness.com" },
      { name: "Endura", meaning: "Endurance — training built for the long game", score: 85, domain: "endura.co" },
      { name: "Strive Lab", meaning: "The laboratory of effort — methodical, evidence-based training", score: 83, domain: "strivelab.com" },
      { name: "Flux Fitness", meaning: "Flux — always moving, always adapting, never static", score: 82, domain: "fluxfitness.com" },
      { name: "Zenta", meaning: "Zen + ta — mindful movement for mental and physical balance", score: 84, domain: "zenta.co" },
      { name: "Pulsar Training", meaning: "Pulsar — high-energy bursts of training that transform performance", score: 86, domain: "pulsartraining.com" },
      { name: "Luminos Wellness", meaning: "Luminous — glowing health from the inside out", score: 85, domain: "luminoswellness.com" },
      { name: "Primal Motion", meaning: "Back to primal — natural, functional movement patterns", score: 87, domain: "primalmotion.com" },
      { name: "Tenace", meaning: "Tenacious — the relentless pursuit of physical excellence", score: 84, domain: "tenace.co" },
      { name: "CoreRise", meaning: "Rising from your core strength outward — foundational fitness", score: 83, domain: "corerise.com" },
      { name: "Formist", meaning: "Form + ist — the specialist in perfect movement form", score: 82, domain: "formist.com" },
      { name: "Velo Fit", meaning: "Velocity + fit — speed-based training methodology", score: 80, domain: "velofit.com" },
      { name: "Resilient", meaning: "Resilience as the foundation of all physical performance", score: 88, domain: "resilient.co" },
      { name: "Halo Wellness", meaning: "Halo — surrounding yourself with complete wellbeing", score: 84, domain: "halowellness.com" },
      { name: "Fortis", meaning: "Latin for strong — strength as the basis for everything", score: 85, domain: "fortis.co" },
      { name: "Kentic", meaning: "Kinetic — movement is medicine, and we prescribe it daily", score: 83, domain: "kentic.co" },
      { name: "Groundswell", meaning: "The groundswell of movement — community-powered fitness", score: 82, domain: "groundswell.co" },
      { name: "Paceframe", meaning: "Your pace, your framework — personalised training methodology", score: 81, domain: "paceframe.com" },
      { name: "Solstice Wellness", meaning: "The turning point — where your wellness journey reaches a new peak", score: 84, domain: "solsticewellness.com" },
      { name: "Outform", meaning: "Out-perform your previous form — progressive overload philosophy", score: 86, domain: "outform.co" },
      { name: "Kinetica", meaning: "Kinetics — the science of movement applied to every workout", score: 85, domain: "kinetica.co" },
      { name: "Momentum Labs", meaning: "Building momentum that compounds — sustainable fitness gains", score: 83, domain: "momentumlabs.com" },
    ],
  },
  {
    slug: "saas",
    niche: "SaaS & Developer Tools",
    metaTitle: "150 SaaS Startup Name Ideas (With Domains) | NamoLux",
    metaDescription: "Find 150 SaaS startup name ideas with Founder Signal scores and domain suggestions. Discover a clean, memorable name for your software-as-a-service product.",
    h1: "SaaS Startup Name Ideas: 150 Names for Software & Developer Tool Companies",
    intro: "SaaS names need to balance technical credibility with approachability. Developer tools can lean more technical; consumer SaaS needs warmth and clarity. The best SaaS names are short invented words or metaphors that hint at the core value without being literal — think Notion, Linear, Vercel, or Loom. Here are 150 name ideas for SaaS products and developer tools.",
    namingTips: [
      ".io is widely accepted for SaaS and dev tools — .com is still the gold standard",
      "Avoid describing the feature; name the feeling or outcome your product delivers",
      "Short names (5-8 chars) index and search better, and fit better in nav and product UI",
      "Test the name with a developer — if they think it's cool, it's probably good",
    ],
    names: [
      { name: "Lineate", meaning: "Line + ate — bringing linear clarity to complex software workflows", score: 86, domain: "lineate.io" },
      { name: "Stackly", meaning: "Stack — building the best possible software stack, simply", score: 84, domain: "stackly.io" },
      { name: "Flowbit", meaning: "Flow + bit — the smallest unit of seamless workflow automation", score: 85, domain: "flowbit.io" },
      { name: "Nodalx", meaning: "Node + al — the modular building block of your software architecture", score: 83, domain: "nodalx.io" },
      { name: "Veritas", meaning: "Latin: truth — software you can rely on absolutely", score: 87, domain: "veritas.io" },
      { name: "Draftly", meaning: "Draft — build, iterate, and ship products faster", score: 82, domain: "draftly.io" },
      { name: "Shipfast", meaning: "Ship fast — the ethos of high-velocity product development", score: 85, domain: "shipfast.io" },
      { name: "Rendex", meaning: "Render + ex — fast, clean rendering infrastructure for developers", score: 83, domain: "rendex.io" },
      { name: "Pulseio", meaning: "The live pulse of your product — real-time metrics and monitoring", score: 86, domain: "pulseio.com" },
      { name: "Archway", meaning: "The architectural gateway — infrastructure that holds everything up", score: 84, domain: "archway.io" },
      { name: "Kernal", meaning: "Kernel — the core of your operating logic, exposed and optimised", score: 85, domain: "kernal.io" },
      { name: "Terrabit", meaning: "Terra + bit — grounding digital infrastructure at massive scale", score: 82, domain: "terrabit.io" },
      { name: "Flotiq", meaning: "Float + iq — intelligent content infrastructure that floats above complexity", score: 84, domain: "flotiq.io" },
      { name: "Praxis", meaning: "Practice made perfect — developer tooling built from real use cases", score: 88, domain: "praxis.io" },
      { name: "Composit", meaning: "Composable — modular software that assembles into anything", score: 83, domain: "composit.io" },
      { name: "Launchly", meaning: "Launch — the whole toolkit to go from code to customers", score: 85, domain: "launchly.io" },
      { name: "Flagbase", meaning: "Flag + base — feature flag infrastructure at the base of your stack", score: 84, domain: "flagbase.io" },
      { name: "Coherent", meaning: "Coherent — where all your services finally work as one", score: 86, domain: "coherent.io" },
      { name: "Byteform", meaning: "Byte + form — transforming raw bytes into meaningful software", score: 82, domain: "byteform.io" },
      { name: "Scaffold", meaning: "The scaffolding for your entire product — structure before features", score: 83, domain: "scaffold.io" },
      { name: "Nexlayer", meaning: "Next layer — the abstraction layer your software has been waiting for", score: 85, domain: "nexlayer.io" },
      { name: "Streamline", meaning: "Streamlined processes — no waste, no friction, just output", score: 87, domain: "streamline.io" },
      { name: "Coderaft", meaning: "Code + raft — the vessel that carries your code safely to production", score: 83, domain: "coderaft.io" },
      { name: "Plinth", meaning: "The base, the plinth — foundational software infrastructure", score: 84, domain: "plinth.io" },
      { name: "Trellis", meaning: "The trellis — the structure that guides product growth in the right direction", score: 82, domain: "trellis.io" },
      { name: "Siphon", meaning: "Siphon — drawing data from anywhere and delivering it everywhere", score: 81, domain: "siphon.io" },
      { name: "Boltform", meaning: "Bolt + form — lightning-fast form and data collection infrastructure", score: 83, domain: "boltform.io" },
      { name: "Crestdb", meaning: "Crest + db — peak-performance database infrastructure", score: 82, domain: "crestdb.io" },
      { name: "Proxima", meaning: "Proxima (nearest) — the closest, most accessible developer toolchain", score: 84, domain: "proxima.io" },
      { name: "Dockside", meaning: "Dockside — where your containers, services, and pipelines are managed", score: 81, domain: "dockside.io" },
    ],
  },
  {
    slug: "ecommerce",
    niche: "Ecommerce & Retail",
    metaTitle: "150 Ecommerce Brand Name Ideas (With Domains) | NamoLux",
    metaDescription: "Browse 150 ecommerce brand name ideas with Founder Signal scores and domain suggestions. Find a memorable name for your online store or retail brand.",
    h1: "Ecommerce Brand Name Ideas: 150 Names for Online Stores & Retail Brands",
    intro: "Ecommerce brand names have to do a lot of work — they need to convey product quality, build trust at first glance, and be easy to search and remember when someone wants to come back. The best ecommerce names are short, evocative, and hint at the category without being generic. Whether you're building a niche DTC brand or a broad marketplace, your name is your first impression. Here are 150 ecommerce name ideas.",
    namingTips: [
      "Customer trust is critical — names that sound established outperform clever wordplay",
      "Consider how the name reads on product packaging, emails, and ads",
      "Descriptive + adjective combinations work well: Smooth Thread, Bold Basket, etc.",
      ".com is strongly preferred for ecommerce — customers associate it with legitimate stores",
    ],
    names: [
      { name: "Cartify", meaning: "Cart + ify — making the shopping cart experience seamless", score: 84, domain: "cartify.com" },
      { name: "Shopvault", meaning: "Shop + vault — a curated collection of premium products", score: 82, domain: "shopvault.com" },
      { name: "Orderley", meaning: "Order + ly — clean, organised buying from a trustworthy store", score: 80, domain: "orderley.com" },
      { name: "Plentiful", meaning: "Abundance — a store with everything you need", score: 83, domain: "plentiful.co" },
      { name: "Cratebox", meaning: "Crate + box — curated subscription boxes delivered with care", score: 85, domain: "cratebox.com" },
      { name: "Marktly", meaning: "Market + ly — your local market, scaled to the internet", score: 81, domain: "marktly.com" },
      { name: "Nuvella", meaning: "Novel + a — fresh, new products discovered first here", score: 84, domain: "nuvella.com" },
      { name: "Trove", meaning: "A trove — discovered treasures worth owning", score: 88, domain: "trove.co" },
      { name: "Stockd", meaning: "Stocked — always in stock, always shipped fast", score: 82, domain: "stockd.com" },
      { name: "Haul", meaning: "The haul — everything you wanted, delivered", score: 84, domain: "haul.co" },
      { name: "Wander Market", meaning: "Discovering products from unexpected places around the world", score: 83, domain: "wandermarket.com" },
      { name: "Fetchly", meaning: "Fetch — we find the best products so you don't have to", score: 80, domain: "fetchly.com" },
      { name: "Brandwell", meaning: "Well-branded products from brands that care about quality", score: 82, domain: "brandwell.co" },
      { name: "Stockroom", meaning: "Your curated stockroom — quality products, fair prices", score: 79, domain: "stockroom.co" },
      { name: "Luminary Shop", meaning: "Products that illuminate your life — bright choices", score: 83, domain: "luminaryshop.com" },
      { name: "Crafted", meaning: "Thoughtfully crafted products — not mass produced", score: 87, domain: "crafted.co" },
      { name: "Outpost Store", meaning: "The remote outpost — discovering products off the beaten path", score: 81, domain: "outpoststore.com" },
      { name: "Velvetly", meaning: "Smooth, premium — luxury goods accessible to everyone", score: 84, domain: "velvetly.com" },
      { name: "Selecta", meaning: "Selected — every product hand-picked for quality", score: 83, domain: "selecta.co" },
      { name: "Bundlehaus", meaning: "Bundle + haus — curated product bundles with European quality cues", score: 80, domain: "bundlehaus.com" },
      { name: "Ember Goods", meaning: "Warm, considered goods that become part of your daily life", score: 84, domain: "embergoods.com" },
      { name: "Terrace", meaning: "An elevated vantage point — premium products with a view", score: 82, domain: "terrace.co" },
      { name: "Fillr", meaning: "Fill — the store that fills your home, wardrobe, or workflow", score: 81, domain: "fillr.co" },
      { name: "Pinnacle Goods", meaning: "Peak quality — products at the pinnacle of their category", score: 83, domain: "pinnaclegoods.com" },
      { name: "Stackhaus", meaning: "Stack — everything you need, stacked in one store", score: 80, domain: "stackhaus.com" },
      { name: "Cultivate Shop", meaning: "Cultivated taste — products chosen with intention", score: 82, domain: "cultivateshop.com" },
      { name: "Groundwork", meaning: "The foundation — essential products for everyday excellence", score: 81, domain: "groundwork.co" },
      { name: "Originals Club", meaning: "Only originals — authentic, genuine products, never counterfeit", score: 83, domain: "originalsclub.com" },
      { name: "Vault Supply", meaning: "From the vault — quality-locked products worth the investment", score: 82, domain: "vaultsupply.com" },
      { name: "Basecamp Store", meaning: "Your basecamp — essential gear and goods for life's adventures", score: 80, domain: "basecampstore.com" },
    ],
  },
  {
    slug: "real-estate",
    niche: "Real Estate & Property",
    metaTitle: "150 Real Estate Business Name Ideas (With Domains) | NamoLux",
    metaDescription: "Find 150 real estate business name ideas with Founder Signal scores and domain suggestions. Discover a credible, memorable name for your property company.",
    h1: "Real Estate Business Name Ideas: 150 Names for Property & Real Estate Companies",
    intro: "Real estate brand names need to project trust, local knowledge, and professionalism — but in a market flooded with generic 'Homes' and 'Properties' suffixes, the businesses that stand out have names that convey a philosophy or personality. Whether you're a solo agent, a PropTech startup, or a luxury developer, your name is your reputation before the first handshake. Here are 150 real estate business name ideas.",
    namingTips: [
      "Geographic names work well for local agencies but limit scaling — plan ahead",
      "PropTech companies should lean toward clean, modern names over traditional real estate language",
      "Trust and permanence are key brand values — names evoking roots, foundation, and solidity work well",
      ".com is essential for real estate — clients expect it and trust it implicitly",
    ],
    names: [
      { name: "Cornerstone Realty", meaning: "The cornerstone — the fundamental, trusted base of property transactions", score: 87, domain: "cornerstonerealty.com" },
      { name: "Meridian Property", meaning: "The highest point — premium property at the peak of the market", score: 85, domain: "meridianproperty.com" },
      { name: "Hearthstone", meaning: "The hearth — the warm, welcoming heart of every home", score: 86, domain: "hearthstone.co" },
      { name: "Foundry Homes", meaning: "Where homes are forged — built with strength and purpose", score: 84, domain: "foundryhomes.com" },
      { name: "Landmark Living", meaning: "Landmark — memorable properties in remarkable locations", score: 83, domain: "landmarkliving.com" },
      { name: "Groundfloor", meaning: "Get in on the ground floor — accessible property investment", score: 85, domain: "groundfloor.co" },
      { name: "Plinth Realty", meaning: "Plinth — the foundational layer of your property portfolio", score: 82, domain: "plinthrealty.com" },
      { name: "Homeward", meaning: "Always heading homeward — guiding buyers to the right place", score: 84, domain: "homeward.co" },
      { name: "Keystone Group", meaning: "The keystone — the critical piece that holds everything together", score: 86, domain: "keystonegroup.co" },
      { name: "Solstice Estates", meaning: "The turning point — where you find your perfect property", score: 83, domain: "solsticeestates.com" },
      { name: "Opengate", meaning: "Open gate — welcoming access to new homes and investments", score: 82, domain: "opengate.co" },
      { name: "Terra Nova", meaning: "New land — fresh opportunities in property and development", score: 87, domain: "terranova.co" },
      { name: "Dwell", meaning: "To dwell — homes and spaces worth truly living in", score: 89, domain: "dwell.co" },
      { name: "Abode Collective", meaning: "A collective of exceptional homes and the people who love them", score: 84, domain: "abodecollective.com" },
      { name: "Roofline Realty", meaning: "The roofline — we see the whole picture from the top down", score: 82, domain: "rooflinerealty.com" },
      { name: "Estoria", meaning: "Estate + story — every property has a story worth telling", score: 83, domain: "estoria.co" },
      { name: "Threshhold", meaning: "The threshold — we help you cross into your next chapter", score: 85, domain: "threshhold.co" },
      { name: "Verdant Properties", meaning: "Verdant — lush, thriving properties in desirable locations", score: 83, domain: "verdantproperties.com" },
      { name: "Elevate Estates", meaning: "Elevated living — premium properties for discerning buyers", score: 84, domain: "elevateestates.com" },
      { name: "Anchor Realty", meaning: "Anchor — the stable, trusted guide through property transactions", score: 85, domain: "anchorrealty.com" },
      { name: "Strata Living", meaning: "Strata — layered property investment and development", score: 82, domain: "strataliving.com" },
      { name: "Homebase Co", meaning: "Your homebase — the starting point for every property decision", score: 84, domain: "homebaseco.com" },
      { name: "Clearview Homes", meaning: "Clear view — transparent process, exceptional properties", score: 83, domain: "clearviewhomes.com" },
      { name: "Latitude", meaning: "The latitude to choose — wide range of exceptional properties", score: 86, domain: "latitude.co" },
      { name: "Pinehurst Realty", meaning: "Established, reliable, rooted — like the great pines", score: 81, domain: "pinehurstrealty.com" },
      { name: "Skyrise Group", meaning: "Skyrise — premium developments reaching for the sky", score: 83, domain: "skyrisegroup.com" },
      { name: "Terrace & Co", meaning: "The terrace — elevated property with the best views", score: 82, domain: "terraceco.com" },
      { name: "Stronghold", meaning: "The stronghold — property investments built to last", score: 84, domain: "stronghold.co" },
      { name: "Nestward", meaning: "Heading nestward — always finding the right home", score: 85, domain: "nestward.com" },
      { name: "Blueprint Realty", meaning: "Blueprint — the master plan for your property journey", score: 83, domain: "blueprintrealty.com" },
    ],
  },
  {
    slug: "health",
    niche: "Health & Medical",
    metaTitle: "150 Health Startup Name Ideas (With Domains) | NamoLux",
    metaDescription: "Browse 150 health startup name ideas with Founder Signal scores and domain suggestions. Find a credible, approachable name for your health or medical company.",
    h1: "Health Startup Name Ideas: 150 Names for Health, Medical & Wellness Companies",
    intro: "Health brand names carry enormous responsibility. They need to project clinical credibility while remaining warm and approachable to patients and consumers. The best health brand names balance trust with humanity — they sound like they understand people, not just conditions. Whether you're building a digital health platform, a wellness app, or a medtech company, your name is the first thing patients and investors will judge. Here are 150 health startup name ideas.",
    namingTips: [
      "Avoid medical jargon unless targeting clinicians — patient-facing brands need warmth",
      "Names evoking vitality, clarity, and renewal perform strongly in consumer health",
      "Check regulatory implications — 'health', 'medical', 'clinic' have specific legal uses in some jurisdictions",
      ".com or .health TLD (if relevant) work best — .io can feel too technical for patient-facing brands",
    ],
    names: [
      { name: "Vivara Health", meaning: "Vivid + ara — vibrant, alive, full of vitality", score: 88, domain: "vivarahealth.com" },
      { name: "Claria Med", meaning: "Clarity — clear diagnosis, clear treatment, clear outcomes", score: 86, domain: "clariamed.com" },
      { name: "Luminos Health", meaning: "Luminous — the light of good health from the inside out", score: 87, domain: "luminoshealth.com" },
      { name: "Novela Health", meaning: "Novel + a — innovative health solutions that feel new", score: 84, domain: "novelahealth.com" },
      { name: "Solace", meaning: "Solace — comfort, relief, and healing for patients", score: 89, domain: "solace.co" },
      { name: "Vitalix", meaning: "Vitality + ix — optimising the vital signs of your health", score: 85, domain: "vitalix.com" },
      { name: "Menda", meaning: "Mend + a — healing and restoration as a philosophy", score: 83, domain: "menda.co" },
      { name: "Carely", meaning: "Care + ly — care delivered with kindness and consistency", score: 82, domain: "carely.co" },
      { name: "Heartica", meaning: "Heart + ica — heart-centred healthcare and cardiology", score: 84, domain: "heartica.com" },
      { name: "Aleva Health", meaning: "Alleviate + a — alleviating health concerns with precision", score: 85, domain: "alevahealth.com" },
      { name: "Renova", meaning: "Renew + a — renovation of your health from the inside out", score: 87, domain: "renova.co" },
      { name: "Kinewell", meaning: "Kinetic + well — movement as the path to wellness", score: 83, domain: "kinewell.com" },
      { name: "Thrive MD", meaning: "Thrive — clinical support to help patients truly flourish", score: 86, domain: "thrivemd.com" },
      { name: "Auris Health", meaning: "Auris (Latin: ear) — specialist hearing and ENT health", score: 82, domain: "aurishealth.com" },
      { name: "Mendiq", meaning: "Mend + iq — intelligent healing protocols for faster recovery", score: 84, domain: "mendiq.com" },
      { name: "Cordia Health", meaning: "Cor (heart) + dia — heart-led care for every patient", score: 85, domain: "cordiahealth.com" },
      { name: "Wellform", meaning: "Well + form — shaping the best version of your health", score: 83, domain: "wellform.co" },
      { name: "Pristine Health", meaning: "Pristine — health at its cleanest, purest best", score: 82, domain: "pristinehealth.com" },
      { name: "Calmara", meaning: "Calm + ara — mental health support with warmth and clarity", score: 84, domain: "calmara.co" },
      { name: "Healthward", meaning: "Heading healthward — always moving toward better outcomes", score: 83, domain: "healthward.com" },
      { name: "Meridia", meaning: "Meridian — the midpoint of optimal health and performance", score: 85, domain: "meridia.co" },
      { name: "Balancera", meaning: "Balance + ra — restoring balance as the root of wellbeing", score: 84, domain: "balancera.co" },
      { name: "Nucleus Health", meaning: "The nucleus — core health diagnostics and treatment", score: 83, domain: "nucleushealth.com" },
      { name: "Elara Care", meaning: "Elara (Jupiter's moon) — orbital care for your health ecosystem", score: 82, domain: "elaracare.com" },
      { name: "Nourish AI", meaning: "Nourish — AI-powered nutritional and preventive health guidance", score: 85, domain: "nourishai.com" },
      { name: "Wellpath", meaning: "The well path — your personalised route to better health", score: 84, domain: "wellpath.co" },
      { name: "Clarity Care", meaning: "Clear diagnosis, clear plan, clear outcomes — no confusion", score: 83, domain: "claritycare.com" },
      { name: "Fortis Health", meaning: "Fortis (strong) — building robust health from the foundations", score: 86, domain: "fortishealth.com" },
      { name: "Lifeform Health", meaning: "Life + form — shaping a longer, fuller life through medicine", score: 82, domain: "lifeformhealth.com" },
      { name: "Revita", meaning: "Revitalise — restoring energy, health, and quality of life", score: 85, domain: "revita.co" },
    ],
  },
  {
    slug: "podcast",
    niche: "Podcast & Media",
    metaTitle: "150 Podcast & Media Brand Name Ideas (With Domains) | NamoLux",
    metaDescription: "Discover 150 podcast and media brand name ideas with Founder Signal scores and domain suggestions. Find an unforgettable name for your show, network, or media brand.",
    h1: "Podcast & Media Brand Name Ideas: 150 Names for Shows, Networks & Content Brands",
    intro: "Podcast and media brand names need to be immediately memorable and work both visually (as cover art) and audibly (as the name the host says at the top of every episode). The best podcast names are specific, bold, and hint at the core value proposition — whether that's insight, entertainment, community, or niche expertise. Here are 150 name ideas for podcasts, media companies, and content brands.",
    namingTips: [
      "Say the name out loud 10 times — if it flows naturally, it's good podcast material",
      "Specificity outperforms generic names dramatically in podcast discovery",
      "Consider the cover art implication — does the name work as a visual brand?",
      ".com is preferred for media brands; .fm is a legitimate, well-recognised audio alternative",
    ],
    names: [
      { name: "Signal & Noise", meaning: "Cutting through the noise to find the real signal — clarity in chaos", score: 88, domain: "signalandnoise.com" },
      { name: "The Long Game", meaning: "Patient thinking, long-horizon decisions — depth over clicks", score: 87, domain: "thelonggame.fm" },
      { name: "Unscripted", meaning: "Real conversations, raw insight — no teleprompters", score: 85, domain: "unscripted.fm" },
      { name: "First Principles", meaning: "Reasoning from the ground up — foundational thinking on any topic", score: 89, domain: "firstprinciples.fm" },
      { name: "The Frequency", meaning: "Your frequency — tuning into the right ideas and conversations", score: 86, domain: "thefrequency.fm" },
      { name: "Dispatch Media", meaning: "Timely, sharp dispatches from the frontline of your industry", score: 84, domain: "dispatchmedia.com" },
      { name: "Open Loop", meaning: "Conversations that leave loops open — thinking you can't stop", score: 83, domain: "openloop.fm" },
      { name: "The Brief", meaning: "Smart, concise — the brief you need before your day starts", score: 87, domain: "thebrief.fm" },
      { name: "Meridian Radio", meaning: "The highest point — conversations at peak depth and clarity", score: 84, domain: "meridianradio.com" },
      { name: "Foundry Stories", meaning: "Where ideas are forged — stories of builders and makers", score: 85, domain: "foundrystories.com" },
      { name: "Momentum Radio", meaning: "Conversations that build momentum — for founders and creators", score: 83, domain: "momentumradio.com" },
      { name: "Candid", meaning: "Honest, direct, unrehearsed — the conversations people actually want", score: 86, domain: "candid.fm" },
      { name: "The Upstream", meaning: "Going upstream — finding the source of ideas before they go mainstream", score: 87, domain: "theupstream.fm" },
      { name: "Groundwork Media", meaning: "Laying the groundwork — deep-dive content worth your time", score: 83, domain: "groundworkmedia.com" },
      { name: "Synthesis", meaning: "Synthesising the best ideas across disciplines into clarity", score: 85, domain: "synthesis.fm" },
      { name: "The Nucleus", meaning: "The central, irreducible core of every topic we cover", score: 84, domain: "thenucleus.fm" },
      { name: "Calibrate", meaning: "Getting calibrated — adjusting your thinking with every episode", score: 86, domain: "calibrate.fm" },
      { name: "Archive Media", meaning: "Building the archive — stories and ideas worth preserving", score: 82, domain: "archivemedia.com" },
      { name: "The Precipice", meaning: "At the edge of the next big thing — future-forward media", score: 84, domain: "theprecipice.fm" },
      { name: "Wavelength", meaning: "On the same wavelength — content for people who think deeply", score: 87, domain: "wavelength.fm" },
      { name: "Benchmark Media", meaning: "Setting the benchmark — the standard-setting media brand", score: 83, domain: "benchmarkmedia.com" },
      { name: "Tangent", meaning: "Going off on the right tangent — unexpected but essential ideas", score: 82, domain: "tangent.fm" },
      { name: "The Feed", meaning: "The essential feed — curated, quality content delivered consistently", score: 84, domain: "thefeed.fm" },
      { name: "Pillar Media", meaning: "Pillar content — the foundational content every audience needs", score: 83, domain: "pillarmedia.com" },
      { name: "Deep Cut", meaning: "The deep cuts — the content the algorithm won't show you", score: 85, domain: "deepcut.fm" },
      { name: "The Craft", meaning: "Dedicated to the craft — mastery content for serious practitioners", score: 86, domain: "thecraft.fm" },
      { name: "Origin Stories", meaning: "The origin stories — how the best ideas and companies were born", score: 87, domain: "originstories.fm" },
      { name: "Plainspeak", meaning: "No jargon, no fluff — plain speaking on complex topics", score: 84, domain: "plainspeak.fm" },
      { name: "Undercurrent", meaning: "The undercurrent — the forces shaping your world beneath the surface", score: 85, domain: "undercurrent.fm" },
      { name: "The Meridian", meaning: "The highest point of the day — the media brand you turn to first", score: 83, domain: "themeridian.fm" },
    ],
  },
  {
    slug: "coffee-shop",
    niche: "Coffee Shop & Café",
    metaTitle: "150 Coffee Shop Name Ideas (With Domains) | NamoLux",
    metaDescription: "Browse 150 coffee shop and café name ideas with Founder Signal scores and domain suggestions. Find a warm, memorable name for your coffee brand.",
    h1: "Coffee Shop Name Ideas: 150 Names for Cafés, Coffee Brands & Roasteries",
    intro: "A coffee shop name needs to feel like the first sip — warm, inviting, and impossible to forget. The best café names evoke a feeling, a ritual, or a place people want to belong to. They work on a takeaway cup, a neon sign, and an Instagram bio equally well. Whether you're opening a neighbourhood café, a specialty roastery, or a coffee subscription brand, your name sets the mood before customers walk through the door.",
    namingTips: [
      "Test the name on a blank coffee cup — it needs to look and feel right",
      "Names with warmth, ritual, or belonging outperform clever wordplay for local cafés",
      "For roasteries and DTC coffee brands, origin cues and craft language perform well",
      ".com or .co works well; for local cafés, a geographic suffix can build community identity",
    ],
    names: [
      { name: "Common Ground", meaning: "Where everyone belongs — coffee as common ground", score: 89, domain: "commonground.co" },
      { name: "Ember & Bean", meaning: "The warmth of embers and the richness of the bean", score: 88, domain: "emberandbean.com" },
      { name: "Groundwork Coffee", meaning: "The groundwork of your day — ritual, craft, community", score: 87, domain: "groundworkcoffee.com" },
      { name: "Forage", meaning: "Foraging for the finest beans — small-batch, sourced with care", score: 85, domain: "forage.co" },
      { name: "The Hearth", meaning: "The hearth — the warm centre everyone gathers around", score: 86, domain: "thehearth.co" },
      { name: "First Light Coffee", meaning: "The first light of morning — your most essential daily ritual", score: 87, domain: "firstlightcoffee.com" },
      { name: "Coalfire Roasters", meaning: "Slow-roasted, intense, character-full coffee", score: 84, domain: "coalfireroasters.com" },
      { name: "Ritual", meaning: "Coffee as ritual — the ceremony worth repeating every morning", score: 88, domain: "ritual.co" },
      { name: "Raven Coffee", meaning: "Dark, intelligent, bold — coffee for the thoughtful", score: 85, domain: "ravencoffee.com" },
      { name: "The Kettle Room", meaning: "Warm, unhurried, honest — a café that feels like a friend's kitchen", score: 83, domain: "thekettleroom.com" },
      { name: "Steep & Co", meaning: "The art of the steep — coffee and tea with patience and precision", score: 84, domain: "steepco.com" },
      { name: "Dusk Coffee", meaning: "The evening version of your morning ritual — anytime coffee", score: 82, domain: "duskcoffee.com" },
      { name: "Anchor Coffee", meaning: "Your anchor — the constant in a changing day", score: 86, domain: "anchorcoffee.com" },
      { name: "Lowlight Roasters", meaning: "The low, warm light of early morning — intimate specialty coffee", score: 84, domain: "lowlightroasters.com" },
      { name: "Sunday Morning", meaning: "Every cup feels like Sunday morning — unhurried, perfect", score: 87, domain: "sundaymorning.co" },
      { name: "Wildroast", meaning: "Wild + roast — untamed flavour from carefully wild-grown beans", score: 85, domain: "wildroast.com" },
      { name: "Presswork Coffee", meaning: "The press — hand-crafted, methodical coffee at its best", score: 83, domain: "pressworkcoffee.com" },
      { name: "Current Coffee", meaning: "Always current — freshly roasted, freshly brewed", score: 82, domain: "currentcoffee.com" },
      { name: "The Origin", meaning: "Back to origin — single-origin beans with provenance and story", score: 84, domain: "theorigin.co" },
      { name: "Solstice Coffee", meaning: "The peak — coffee that marks the high point of your day", score: 85, domain: "solsticecoffee.com" },
      { name: "Notes Coffee", meaning: "Tasting notes, music notes — a café with culture at its core", score: 83, domain: "notescoffee.com" },
      { name: "Loft Coffee", meaning: "An elevated, airy space — coffee with views and good lighting", score: 84, domain: "loftcoffee.com" },
      { name: "The Foundry Cup", meaning: "Where great coffee is forged — a serious brewing operation", score: 82, domain: "thefoundrycup.com" },
      { name: "Harbourside Coffee", meaning: "The harbour — a welcoming stop on your daily journey", score: 81, domain: "harboursidecoffee.com" },
      { name: "Steady State", meaning: "The ideal state — your coffee-fuelled flow throughout the day", score: 83, domain: "steadystate.co" },
      { name: "Blueprint Coffee", meaning: "The blueprint for a perfect day — starts with the perfect cup", score: 82, domain: "blueprintcoffee.com" },
      { name: "The Perch", meaning: "Your perch — the spot you claim every morning", score: 85, domain: "theperch.co" },
      { name: "Woodfire Roasters", meaning: "Old-world craftsmanship — woodfire character in every bag", score: 84, domain: "woodfireroasters.com" },
      { name: "Quarter Moon", meaning: "The quarter moon — late-night coffee for the people still working", score: 83, domain: "quartermoon.co" },
      { name: "The Gather", meaning: "Where people gather — coffee as a reason to come together", score: 86, domain: "thegather.co" },
    ],
  },
  {
    slug: "gaming",
    niche: "Gaming & Esports",
    metaTitle: "150 Gaming Startup & Studio Name Ideas (With Domains) | NamoLux",
    metaDescription: "Find 150 gaming company and esports name ideas with Founder Signal scores and domain suggestions. Discover a bold name for your game studio or esports brand.",
    h1: "Gaming Studio & Esports Name Ideas: 150 Names for Game Studios & Gaming Brands",
    intro: "Gaming brand names need edge, energy, and a memorable visual identity before you've shown a single screenshot. The best game studio names project the kind of world they create — epic, precise, dark, or playful — while being distinct enough to stand out in the loudest, most attention-saturated market online. Here are 150 name ideas for game studios, esports organisations, and gaming brands.",
    namingTips: [
      "Hard consonants (K, X, V, Z) project power — essential for action and esports brands",
      "Fantasy names work for RPG studios; clinical names suit strategy games; playful names suit indie",
      ".gg is the dominant TLD for esports and gaming brands — widely recognised",
      "Check Twitch and YouTube handle availability — you'll need them from day one",
    ],
    names: [
      { name: "Ironclad Studios", meaning: "Unbreakable, powerful — games built with armoured precision", score: 89, domain: "ironcladstudios.com" },
      { name: "Vortex Gaming", meaning: "The vortex — pulling players into immersive, unstoppable worlds", score: 87, domain: "vortex.gg" },
      { name: "Nexus Games", meaning: "The nexus — the central hub where gaming worlds connect", score: 85, domain: "nexusgames.com" },
      { name: "Apex Legion", meaning: "Peak performance — an elite legion of competitive players", score: 88, domain: "apexlegion.gg" },
      { name: "Crux Studios", meaning: "The crux — games built around the critical moments that matter", score: 84, domain: "cruxstudios.com" },
      { name: "Ember Games", meaning: "The ember — small sparks that become massive gaming worlds", score: 86, domain: "ember.gg" },
      { name: "Forge Interactive", meaning: "Forging the future of gaming — built, not borrowed", score: 85, domain: "forgeinteractive.com" },
      { name: "Obsidian Play", meaning: "Dark, sharp, unbreakable — premium game experiences", score: 84, domain: "obsidianplay.com" },
      { name: "Void Studios", meaning: "The void — vast, unexplored gaming worlds without limits", score: 83, domain: "voidstudios.com" },
      { name: "Phantom Games", meaning: "Phantom — games that haunt you long after you've stopped playing", score: 86, domain: "phantomgames.gg" },
      { name: "Titan Games", meaning: "Titan scale — games with ambition matching the greatest", score: 85, domain: "titangames.gg" },
      { name: "Ravenshard", meaning: "Raven (dark intelligence) + shard (fragment) — a dark RPG studio", score: 83, domain: "ravenshard.com" },
      { name: "Solaris Games", meaning: "Solar system scale — world-building gaming experiences", score: 84, domain: "solarisgames.com" },
      { name: "Shockwave", meaning: "The shockwave — games that send reverberations through the industry", score: 85, domain: "shockwave.gg" },
      { name: "Pinnacle Esports", meaning: "The pinnacle — elite competitive gaming at the highest level", score: 87, domain: "pinnacleesports.com" },
      { name: "Steelpath", meaning: "The steel path — grinding the hardest content, earning every win", score: 83, domain: "steelpath.gg" },
      { name: "Nightfall Games", meaning: "When the sun sets, the real gaming begins — dark, immersive worlds", score: 84, domain: "nightfallgames.com" },
      { name: "Stormgate Studios", meaning: "Through the storm gate — epic, high-stakes game environments", score: 82, domain: "stormgate.gg" },
      { name: "Arcane Works", meaning: "Arcane — the hidden magic of great game design, revealed", score: 85, domain: "arcaneworks.com" },
      { name: "Celestial Games", meaning: "Cosmic scale — games set in the heavens and beyond", score: 83, domain: "celestialgames.com" },
      { name: "Hardlight Games", meaning: "Hard light — crisp, precise, high-performance game visuals", score: 82, domain: "hardlightgames.com" },
      { name: "Fracture Games", meaning: "Breaking the mold — games that fracture genre conventions", score: 84, domain: "fracturegames.com" },
      { name: "Overwatch Studios", meaning: "Watching from above — strategic, commanding game perspectives", score: 83, domain: "overwatchstudios.com" },
      { name: "Ironroot Games", meaning: "Deeply rooted, unshakeable — games with lasting world-building", score: 82, domain: "ironrootgames.com" },
      { name: "Pulse Esports", meaning: "The pulse — real-time competitive gaming at its most intense", score: 84, domain: "pulseesports.gg" },
      { name: "Gravity Well", meaning: "The gravity well — games with irresistible pull", score: 83, domain: "gravitywellgames.com" },
      { name: "Siege Works", meaning: "Methodical, strategic — siege-mode game development", score: 82, domain: "siegeworks.com" },
      { name: "Axiom Games", meaning: "Self-evident excellence — games where quality is the baseline", score: 85, domain: "axiomgames.com" },
      { name: "Strikezone", meaning: "In the zone — competitive gaming in the perfect strike window", score: 83, domain: "strikezone.gg" },
      { name: "Crucible Games", meaning: "The crucible — where great games are forged under pressure", score: 86, domain: "cruciblegames.com" },
    ],
  },
  {
    slug: "travel",
    niche: "Travel & Tourism",
    metaTitle: "150 Travel Startup & Agency Name Ideas (With Domains) | NamoLux",
    metaDescription: "Discover 150 travel brand and agency name ideas with Founder Signal scores and domain suggestions. Find an adventurous, memorable name for your travel company.",
    h1: "Travel Brand Name Ideas: 150 Names for Travel Companies, Agencies & Tourism Brands",
    intro: "Travel brand names should do one thing instantly: make you want to go somewhere. The best travel brand names evoke a feeling — adventure, discovery, ease, or belonging — and make the promise before a word of copy is read. Whether you're building a travel tech platform, a boutique tour operator, or a travel content brand, your name is the first destination. Here are 150 travel brand name ideas.",
    namingTips: [
      "Names evoking movement, discovery, and horizon work better than destination-specific names",
      "Avoid 'travel', 'trips', 'vacations' in isolation — pair with something that creates personality",
      "Consider how the name looks as luggage tags and travel accessories — physical brand touchpoints matter",
      ".com is standard; .travel is an alternative but has limited recognition",
    ],
    names: [
      { name: "Wayfarer", meaning: "The wayfarer — one who travels their own path, unhurried", score: 89, domain: "wayfarer.co" },
      { name: "Horizons", meaning: "Always a new horizon — travel that keeps expanding your world", score: 87, domain: "horizons.co" },
      { name: "Wanderlux", meaning: "Wanderlust + lux — premium, beautiful wandering", score: 88, domain: "wanderlux.com" },
      { name: "Outbound", meaning: "Always outbound — adventures beyond the familiar", score: 86, domain: "outbound.co" },
      { name: "Latitude", meaning: "The latitude to go anywhere — freedom of movement", score: 85, domain: "latitude.co" },
      { name: "The Compass", meaning: "Your compass — always pointing you toward the right experience", score: 87, domain: "thecompass.co" },
      { name: "Voyage", meaning: "The voyage — a journey worth every mile", score: 86, domain: "voyage.co" },
      { name: "Traverse", meaning: "Traverse the world — overland, off-the-beaten-path travel", score: 84, domain: "traverse.co" },
      { name: "Meridian Travel", meaning: "The meridian — travel that crosses time zones and changes you", score: 85, domain: "meridiantravel.com" },
      { name: "Edgewise", meaning: "Getting in edgewise — travelling to the edges of the map", score: 83, domain: "edgewise.co" },
      { name: "Pathfinder", meaning: "Finding the path — curated travel for the genuinely adventurous", score: 86, domain: "pathfinder.co" },
      { name: "The Cartographer", meaning: "Mapping new experiences — travel as personal cartography", score: 84, domain: "thecartographer.com" },
      { name: "Roam", meaning: "Roam freely — travel without rigid itineraries", score: 88, domain: "roam.co" },
      { name: "Farside", meaning: "The far side — destinations beyond the tourist trail", score: 85, domain: "farside.co" },
      { name: "Driftwood", meaning: "Carried by the current — slow, purposeful travel", score: 83, domain: "driftwood.co" },
      { name: "Summit & Sea", meaning: "From summit to sea — every terrain, every experience covered", score: 84, domain: "summitandsea.com" },
      { name: "Basecamp", meaning: "The basecamp — your launch point for extraordinary journeys", score: 86, domain: "basecamp.co" },
      { name: "Nomadly", meaning: "The nomadic way — travel built around living, not visiting", score: 85, domain: "nomadly.co" },
      { name: "Vestigo", meaning: "Latin: trace, track — following the tracks of great journeys", score: 83, domain: "vestigo.co" },
      { name: "Farrow Travel", meaning: "Going to the farthest reaches — remote, remarkable experiences", score: 84, domain: "farrowtravel.com" },
      { name: "Overland", meaning: "The overland journey — travel by surface for those who want to see everything", score: 86, domain: "overland.co" },
      { name: "Trailcraft", meaning: "Crafting the trail — bespoke adventure itineraries", score: 83, domain: "trailcraft.com" },
      { name: "Peregrine", meaning: "The peregrine — swift, far-ranging, purposeful travel", score: 85, domain: "peregrine.co" },
      { name: "Borderless", meaning: "Borderless — travel that ignores artificial limits", score: 86, domain: "borderless.co" },
      { name: "The Circuit", meaning: "The circuit — completing the grand tour with ease and elegance", score: 84, domain: "thecircuit.co" },
      { name: "Landfall", meaning: "Landfall — arriving somewhere new for the first time", score: 83, domain: "landfall.co" },
      { name: "Passage", meaning: "The passage — the journey between who you are and who you'll become", score: 85, domain: "passage.co" },
      { name: "Freeport", meaning: "The free port — a hub of global connection and movement", score: 82, domain: "freeport.co" },
      { name: "Solstice Travel", meaning: "The turning point — journeys that change the direction of your life", score: 84, domain: "solsticetravel.com" },
      { name: "Immerse", meaning: "Total immersion — travel that goes below the surface of a destination", score: 87, domain: "immerse.co" },
    ],
  },
  {
    slug: "consulting",
    niche: "Consulting & Professional Services",
    metaTitle: "150 Consulting Firm Name Ideas (With Domains) | NamoLux",
    metaDescription: "Find 150 consulting firm and professional services name ideas with Founder Signal scores. Discover a credible, distinctive name for your consulting business.",
    h1: "Consulting Firm Name Ideas: 150 Names for Consulting & Professional Services Businesses",
    intro: "Consulting firm names need to project expertise, trust, and clarity. In a market where 'solutions', 'partners', and 'group' are appended to every name, the consultancies that win are those with names that convey a sharp point of view or a memorable image. Whether you're a solo consultant, a boutique firm, or scaling a specialist consultancy, here are 150 name ideas to help you stand out.",
    namingTips: [
      "Single strong words outperform compound generic names for consultancies",
      "Names that suggest outcome or philosophy outperform those that describe the service",
      "Avoid 'solutions', 'partners', 'group', 'associates' unless pairing with a genuinely strong primary word",
      ".com is the only acceptable TLD for professional services — credibility depends on it",
    ],
    names: [
      { name: "Pinnacle Advisory", meaning: "Peak expertise — advisory services at the highest level", score: 87, domain: "pinnacleadvisory.com" },
      { name: "Meridian Partners", meaning: "The meridian — reaching the highest point together", score: 85, domain: "meridianpartners.com" },
      { name: "Keystone Consulting", meaning: "The keystone — the critical piece that holds your strategy together", score: 86, domain: "keystoneconsulting.com" },
      { name: "Axiom Advisory", meaning: "Axiom — self-evident truths applied to complex business problems", score: 84, domain: "axiomadvisory.com" },
      { name: "Vantage Consulting", meaning: "The vantage point — perspective that transforms decisions", score: 85, domain: "vantageconsulting.com" },
      { name: "Prism Strategy", meaning: "Refracting complex challenges into clear, actionable strategy", score: 83, domain: "prismstrategy.com" },
      { name: "Catalyst Group", meaning: "The catalyst — accelerating transformation without being the transformation", score: 84, domain: "catalystgroup.co" },
      { name: "Clarity Works", meaning: "Bringing clarity — from complexity to clear, executable plans", score: 86, domain: "clarityworks.com" },
      { name: "Groundwork Consulting", meaning: "Laying the groundwork — strategic foundations before growth", score: 85, domain: "groundworkconsulting.com" },
      { name: "Nucleus Advisory", meaning: "The nucleus — strategy at the core of everything you do", score: 83, domain: "nucleusadvisory.com" },
      { name: "Firstlight Strategy", meaning: "First light — the early clarity that guides all subsequent decisions", score: 84, domain: "firstlightstrategy.com" },
      { name: "Resonance Consulting", meaning: "Strategy that resonates with your market, team, and mission", score: 86, domain: "resonanceconsulting.com" },
      { name: "Archon Partners", meaning: "Archon (Greek: ruling authority) — leadership-level advisory", score: 83, domain: "archonpartners.com" },
      { name: "Fulcrum Advisory", meaning: "The fulcrum — the leverage point that moves everything else", score: 85, domain: "fulcrumadvisory.com" },
      { name: "Northstar Strategy", meaning: "The north star — the guiding constant in your strategic direction", score: 84, domain: "northstarstrategy.com" },
      { name: "Benchmark Advisory", meaning: "Setting and exceeding benchmarks — evidence-based consulting", score: 83, domain: "benchmarkadvisory.com" },
      { name: "Ironwork Strategy", meaning: "Iron-strength strategy — built to support real weight", score: 82, domain: "ironworkstrategy.com" },
      { name: "Luminary Group", meaning: "Luminaries — thought leaders guiding organisations to clarity", score: 85, domain: "luminarygroup.com" },
      { name: "Strata Advisory", meaning: "Layered thinking — strategy built on solid analytical foundations", score: 83, domain: "strataadvisory.com" },
      { name: "Conduit Consulting", meaning: "The conduit — connecting insight to implementation", score: 84, domain: "conduitconsulting.com" },
      { name: "Crossroads Advisory", meaning: "Clarity at the crossroads — guiding decisive choices", score: 82, domain: "crossroadsadvisory.com" },
      { name: "Leverage", meaning: "The leverage — amplifying every resource for maximum return", score: 86, domain: "leverage.co" },
      { name: "Cornerstone Strategy", meaning: "The cornerstone — the foundational strategic layer", score: 85, domain: "cornerstonestrategy.com" },
      { name: "Orison", meaning: "Prayer, aspiration — consulting built around what clients truly want", score: 83, domain: "orison.co" },
      { name: "Folio Advisory", meaning: "The portfolio — holistic advisory across every business dimension", score: 82, domain: "folioadvisory.com" },
      { name: "Signpost", meaning: "Signposting the path — navigating complexity for clients", score: 84, domain: "signpost.co" },
      { name: "Vanguard Consulting", meaning: "At the vanguard — leading strategy before it becomes conventional", score: 85, domain: "vanguardconsulting.com" },
      { name: "Blueprint Advisory", meaning: "The blueprint — precision-engineered strategy you can execute", score: 84, domain: "blueprintadvisory.com" },
      { name: "Echelon", meaning: "A level above — consulting for organisations ready to step up", score: 83, domain: "echelon.co" },
      { name: "Tenon Advisory", meaning: "Tenon (the joint that connects) — connecting strategy to execution", score: 82, domain: "tenonadvisory.com" },
    ],
  },
  {
    slug: "sustainability",
    niche: "Sustainability & CleanTech",
    metaTitle: "150 Sustainability & CleanTech Startup Name Ideas (With Domains) | NamoLux",
    metaDescription: "Browse 150 sustainability and cleantech startup name ideas with Founder Signal scores and domain suggestions. Find an authentic, impactful name for your green business.",
    h1: "Sustainability & CleanTech Name Ideas: 150 Names for Green, Clean & Impact-Driven Brands",
    intro: "Sustainability brand names must walk a careful line — they need to feel genuinely committed without tipping into greenwashing clichés. The best cleantech and sustainability names are specific, credible, and rooted in the actual impact they create. Avoid vague feel-good words; instead, name the mechanism of change. Here are 150 name ideas for sustainability startups, cleantech companies, and impact-driven brands.",
    namingTips: [
      "Avoid 'eco', 'green', 'sustainable' as standalone names — they're generic and untrustworthy",
      "Name the impact or the mechanism, not the sentiment ('Regenix' not 'GreenGood')",
      "Credibility matters enormously — names that sound scientific or precise build more trust",
      ".com or .earth TLD work well; .earth is gaining recognition in the sustainability space",
    ],
    names: [
      { name: "Terranova", meaning: "New earth — regenerating land and environment through innovation", score: 88, domain: "terranova.co" },
      { name: "Regenix", meaning: "Regenerate + ix — technology that regenerates ecosystems at scale", score: 86, domain: "regenix.com" },
      { name: "Solreed", meaning: "Solar + reed (natural material) — renewable energy with natural roots", score: 84, domain: "solreed.com" },
      { name: "Carbix", meaning: "Carbon + ix — eliminating carbon through systematic innovation", score: 85, domain: "carbix.com" },
      { name: "Verdant Labs", meaning: "Verdant — lush, green science with real-world impact", score: 83, domain: "verdantlabs.com" },
      { name: "Loopclose", meaning: "Close the loop — circular economy at the heart of every product", score: 85, domain: "loopclose.com" },
      { name: "Renewel", meaning: "Renew + el — the elements of renewal powering a cleaner world", score: 83, domain: "renewel.com" },
      { name: "Cedarwood Labs", meaning: "Rooted in nature — sustainable solutions with deep foundations", score: 82, domain: "cedarwoodlabs.com" },
      { name: "Brightflow", meaning: "Bright energy flowing cleanly — renewable infrastructure", score: 84, domain: "brightflow.com" },
      { name: "Terrafirm", meaning: "Terra + firm — solid, dependable climate solutions", score: 85, domain: "terrafirm.com" },
      { name: "Carbona", meaning: "Carbon + na — turning carbon problems into circular solutions", score: 83, domain: "carbona.co" },
      { name: "Mossy", meaning: "Deeply natural, quietly powerful — like moss, it spreads and sustains", score: 81, domain: "mossy.co" },
      { name: "Solstice Energy", meaning: "Harnessing peak solar moments for clean, reliable energy", score: 86, domain: "solsticeenergy.com" },
      { name: "Flowstate Energy", meaning: "Energy in flow — continuous, uninterrupted clean power", score: 84, domain: "flowstateenergy.com" },
      { name: "Ecoria", meaning: "Eco + aria — the song of a healthy ecosystem", score: 82, domain: "ecoria.com" },
      { name: "Groundswell Climate", meaning: "The groundswell of change — climate action building momentum", score: 83, domain: "groundswellclimate.com" },
      { name: "Nexcarbon", meaning: "Next carbon — beyond carbon-neutral to regenerative impact", score: 84, domain: "nexcarbon.com" },
      { name: "Luminary Earth", meaning: "Lighting the way for a cleaner planet through technology", score: 85, domain: "luminaryearth.com" },
      { name: "Roots Tech", meaning: "Technology rooted in earth — climate solutions from the ground up", score: 83, domain: "rootstech.com" },
      { name: "Clearpath Energy", meaning: "The clear path — clean energy with no ambiguity or greenwash", score: 84, domain: "clearpathenerby.com" },
      { name: "Verdex", meaning: "Verdant + ex — green solutions with exponential impact", score: 82, domain: "verdex.com" },
      { name: "Strata Climate", meaning: "Layer by layer — systemic climate solutions built to scale", score: 83, domain: "strataclimate.com" },
      { name: "Bloom Labs", meaning: "Blooming into sustainability — clean innovation that flourishes", score: 84, domain: "bloomlabs.co" },
      { name: "Watershed", meaning: "The watershed moment — climate tech at the turning point", score: 85, domain: "watershed.co" },
      { name: "Restor", meaning: "Restore — land, sea, and air restoration technology", score: 84, domain: "restor.co" },
      { name: "Nuvea", meaning: "Nuvel + ea — new earth energy for a renewed planet", score: 83, domain: "nuvea.com" },
      { name: "Solforge", meaning: "Forging energy from sunlight — robust solar infrastructure", score: 84, domain: "solforge.com" },
      { name: "Crestline Green", meaning: "At the crest — leading green technology from the top down", score: 82, domain: "crestlinegreen.com" },
      { name: "Earthcraft", meaning: "Crafting solutions from and for the earth", score: 85, domain: "earthcraft.co" },
      { name: "Skyward Clean", meaning: "Heading skyward — clean energy reaching new heights", score: 83, domain: "skywardclean.com" },
    ],
  },
]

export function getNicheBySlug(slug: string): NicheData | undefined {
  return pseoNiches.find((n) => n.slug === slug)
}

export function getAllNicheSlugs(): string[] {
  return pseoNiches.map((n) => n.slug)
}

export const nicheCategories = [
  { label: "Technology", slugs: ["ai", "saas", "crypto", "fintech", "gaming"] },
  { label: "Business & Marketing", slugs: ["marketing", "consulting", "ecommerce"] },
  { label: "Lifestyle & Wellness", slugs: ["fitness", "health", "coffee-shop"] },
  { label: "Media & Content", slugs: ["podcast"] },
  { label: "Industry & Place", slugs: ["real-estate", "travel", "sustainability"] },
]
